import { test, expect } from '@playwright/test'
import { mockAccount } from './fixtures/cloud'

test('coach creates a spectator, changes a password, confirms deletion, and replaces an athlete login without losing history', async ({ page }, info) => {
  const { accounts, accountRequests, remote } = await mockAccount(page, 'coach')
  await page.getByRole('link', { name: 'Διαχείριση', exact: true }).filter({ visible: true }).click()
  await expect(page.getByRole('heading', { name: 'Διαχείριση χρηστών.' })).toBeVisible()
  await expect(page.locator('.managed-user')).toHaveCount(3)
  const coach = page.getByRole('region', { name: 'Λογαριασμός Προπονητής', exact: true })
  await expect(coach.getByRole('button')).toHaveCount(0)
  await page.getByRole('button', { name: 'Νέος χρήστης', exact: true }).click()
  const create = page.getByRole('dialog', { name: 'Νέος χρήστης', exact: true })
  await expect(create.getByLabel('Πρόσβαση').locator('option')).toHaveCount(1)
  await create.getByLabel('Όνομα', { exact: true }).fill('Πατέρας')
  await create.getByLabel('Email', { exact: true }).fill('father@example.com')
  await create.getByLabel('Νέος κωδικός', { exact: true }).fill('SecureFather123!')
  await create.getByRole('button', { name: 'Δημιουργία λογαριασμού' }).click()
  await expect(create).not.toBeVisible()
  await expect(page.locator('.managed-user')).toHaveCount(4)
  const father = page.getByRole('region', { name: 'Λογαριασμός Πατέρας', exact: true })
  await expect(father).toContainText('Θεατής')
  await father.getByRole('button', { name: 'Νέος κωδικός Πατέρας', exact: true }).click()
  const reset = page.getByRole('dialog', { name: 'Ορισμός νέου κωδικού' })
  await expect(reset.getByLabel('Νέος κωδικός', { exact: true })).toHaveValue('')
  await reset.getByLabel('Νέος κωδικός', { exact: true }).fill('AnotherSecure123!')
  await reset.getByRole('button', { name: 'Αποθήκευση νέου κωδικού' }).click()
  await expect(reset).not.toBeVisible()
  await expect(page.getByRole('status')).toContainText('Ο νέος κωδικός αποθηκεύτηκε')
  expect(accountRequests.some(r => r.action === 'password')).toBe(true)
  await page.screenshot({ path: `test-results/management-${info.project.name}.png`, fullPage: true })
  await father.getByRole('button', { name: 'Διαγραφή χρήστη Πατέρας' }).click()
  const deletion = page.getByRole('dialog', { name: 'Διαγραφή χρήστη' })
  await deletion.getByRole('button', { name: 'Ακύρωση', exact: true }).click()
  await expect(page.locator('.managed-user')).toHaveCount(4)
  expect(accountRequests.filter(r => r.action === 'delete')).toHaveLength(0)
  await father.getByRole('button', { name: 'Διαγραφή χρήστη Πατέρας' }).click()
  await deletion.getByRole('button', { name: 'Διαγραφή λογαριασμού', exact: true }).click()
  await expect(page.locator('.managed-user')).toHaveCount(3)
  await page.getByRole('button', { name: 'Διαγραφή χρήστη Άννα', exact: true }).click()
  await deletion.getByRole('button', { name: 'Διαγραφή λογαριασμού', exact: true }).click()
  await expect(page.locator('.managed-user')).toHaveCount(2)
  await page.getByRole('button', { name: 'Νέος χρήστης', exact: true }).click()
  await expect(create.getByLabel('Νέος κωδικός', { exact: true })).toHaveValue('')
  await expect(create.getByLabel('Πρόσβαση').locator('option')).toHaveCount(2)
  await create.getByLabel('Πρόσβαση').selectOption('anna')
  await create.getByLabel('Όνομα', { exact: true }).fill('Άννα')
  await create.getByLabel('Email', { exact: true }).fill('new-anna@example.com')
  await create.getByLabel('Νέος κωδικός', { exact: true }).fill('Replacement123!')
  await create.getByRole('button', { name: 'Δημιουργία λογαριασμού' }).click()
  await expect(page.locator('.managed-user')).toHaveCount(3)
  expect([...accounts.values()].some(a => a.email === 'new-anna@example.com')).toBe(true)
  expect(remote.workouts).toHaveLength(1); expect(remote.weighIns).toHaveLength(2)
  const storage = await page.evaluate(() => Object.values(localStorage).join('\n'))
  expect(storage).not.toMatch(/SecureFather123|AnotherSecure123|Replacement123/)
  await page.reload(); await expect(page.locator('.managed-user')).toHaveCount(3)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('management refuses duplicate emails, disables offline actions, and stays gated before backend activation', async ({ page, context }) => {
  const { accountRequests } = await mockAccount(page, 'coach')
  await page.goto('/#/management')
  await expect(page.locator('.managed-user')).toHaveCount(3)
  await page.getByRole('button', { name: 'Νέος χρήστης', exact: true }).click()
  const form = page.getByRole('dialog', { name: 'Νέος χρήστης', exact: true })
  await form.getByLabel('Όνομα', { exact: true }).fill('Duplicate')
  await form.getByLabel('Email', { exact: true }).fill('coach@example.com')
  await form.getByLabel('Νέος κωδικός', { exact: true }).fill('Temporary123!')
  await form.getByRole('button', { name: 'Δημιουργία λογαριασμού' }).click()
  await expect(form.getByRole('alert')).toContainText('χρησιμοποιείται ήδη')
  await form.getByRole('button', { name: 'Ακύρωση', exact: true }).click()
  await context.setOffline(true)
  await expect(page.getByRole('button', { name: 'Νέος χρήστης', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: /^Διαγραφή χρήστη|^Νέος κωδικός / }).first()).toBeDisabled()
  expect(accountRequests.filter(r => r.action === 'create')).toHaveLength(1)
  await context.setOffline(false)
  const legacy = await context.newPage()
  try {
    const old = await mockAccount(legacy, 'coach', true, { accountManagement: false })
    await legacy.goto('/#/management')
    await expect(legacy.getByRole('heading', { name: 'Ενεργοποίηση διαχείρισης' })).toBeVisible()
    await expect(legacy.getByRole('button', { name: 'Νέος χρήστης', exact: true })).toBeDisabled()
    expect(old.accountRequests).toEqual([])
  } finally { await legacy.close() }
})

test('spectators see both athletes saved results and progress with no mutation controls or management route', async ({ page }) => {
  const { requests, accountRequests, workout } = await mockAccount(page, 'spectator')
  await expect(page.getByRole('link', { name: 'Διαχείριση', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Ξεκινήστε προπόνηση' })).toHaveCount(0)
  await page.goto('/#/progress')
  await expect(page.locator('.weighin-table tbody tr')).toHaveCount(2)
  await expect(page.getByRole('button', { name: /^Νέα μέτρηση|^Προσθήκη μέτρησης|^Διόρθωση|^Διαγραφή|^Ορισμός στόχου/ })).toHaveCount(0)
  await page.goto(`/#/history?session=${workout.id}`)
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.locator('.history-athlete.anna')).toBeVisible()
  await expect(page.locator('.history-athlete.dimitra')).toBeVisible()
  await expect(page.getByText('private note', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /^Επεξεργασία|^Διόρθωση|^Διαγραφή/ })).toHaveCount(0)
  await page.goto('/#/program')
  await expect(page.getByRole('button', { name: /Επεξεργασία/ })).toHaveCount(0)
  await page.goto('/#/management')
  await expect(page).toHaveURL(/#\/$/)
  await page.goto(`/#/workout/${workout.id}`)
  await expect(page.getByText('Δεν υπάρχει ενεργή προπόνηση εδώ.', { exact: true })).toBeVisible()
  expect(requests).toEqual([]); expect(accountRequests).toEqual([])
})

test('athletes cannot open management and removed membership ends online app access', async ({ page }) => {
  const { profiles, accountRequests } = await mockAccount(page, 'athlete')
  await expect(page.getByRole('link', { name: 'Διαχείριση', exact: true })).toHaveCount(0)
  await page.goto('/#/management'); await expect(page).toHaveURL(/#\/$/)
  profiles.delete('10000000-0000-0000-0000-000000000002')
  await page.evaluate(() => window.dispatchEvent(new Event('online')))
  await expect(page.getByLabel('Email', { exact: true })).toBeVisible()
  await expect(page.getByRole('status')).toContainText('Δεν βρέθηκε ενεργό προφίλ')
  expect(accountRequests).toEqual([])
})

test('membership refresh preserves cached coach access during a temporary server outage', async ({ page }) => {
  const { workout } = await mockAccount(page, 'coach', true, { active: true })
  await page.goto(`/#/workout/${workout.id}`)
  let checked = false
  await page.route('https://workout-lab-test.supabase.co/rest/v1/profiles*', async route => {
    checked = true
    await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: 'Temporary outage' }) })
  })
  await page.evaluate(() => window.dispatchEvent(new Event('online')))
  await expect.poll(() => checked).toBe(true)
  await expect(page.getByTestId('panel-anna')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Διακοπή', exact: true })).toBeVisible()
  expect(await page.evaluate(() => Boolean(localStorage.getItem('wl-profile:10000000-0000-0000-0000-000000000001')))).toBe(true)
})
