import { test, expect } from '@playwright/test'
import { mockAccount } from './fixtures/cloud'

test('clean action bar gives field feedback, records both pairs and starts rest only on request', async ({ page, context }, info) => {
  const { workout } = await mockAccount(page, 'coach', true, { active: true, configureWorkout: w => { w.results = {} } })
  await page.goto(`/#/workout/${workout.id}`)
  const bar = page.getByTestId('workout-controls'), feedback = bar.getByRole('status', { name: 'Κατάσταση καταγραφής', exact: true })
  const anna = page.getByTestId('panel-anna'), dimitra = page.getByTestId('panel-dimitra')
  await expect(page.locator('.paired-recording, .rest-reminder')).toHaveCount(0)
  await expect(page.locator('.timer-fab')).toBeHidden()
  await expect(page.getByRole('button', { name: 'Άνοιγμα χρονομέτρου', exact: true })).toHaveCount(1)
  await expect(bar.getByRole('button', { name: 'Πίσω', exact: true })).toBeDisabled()
  await expect(feedback).toContainText('Άννα: συμπληρώστε βάρος')
  await expect(feedback).toContainText('Δήμητρα: συμπληρώστε επαναλήψεις')
  await page.getByRole('button', { name: 'Λειτουργία προπόνησης', exact: true }).click()
  await expect(bar.locator('.workout-navigation').getByRole('button')).toHaveCount(3)
  await anna.getByLabel(/^Βάρος/).fill('5')
  await expect(feedback).toContainText('Άννα: συμπληρώστε επαναλήψεις')
  await anna.getByLabel(/^Επαναλήψεις/).fill('10.5')
  await expect(feedback).toContainText('Άννα: ελέγξτε επαναλήψεις')
  await expect(bar.getByRole('button', { name: 'Αλλαγή ασκήσεων', exact: true })).toBeDisabled()
  await anna.getByLabel(/^Επαναλήψεις/).fill('10'); await dimitra.getByLabel(/^Επαναλήψεις/).fill('11')
  await expect(feedback).toHaveText('Έτοιμοι για καταγραφή και αλλαγή.')
  await context.setOffline(true)
  await expect(bar.locator('.workout-sync')).toHaveText('Εκτός σύνδεσης')
  const record = bar.getByRole('button', { name: 'Καταγραφή και αλλαγή', exact: true })
  if (info.project.use.hasTouch) await record.tap(); else await record.click()
  await context.setOffline(false)
  await expect(anna.getByRole('heading', { name: 'TRX Rows', exact: true })).toBeVisible()
  await expect(feedback).toContainText('Δήμητρα: συμπληρώστε βάρος')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await anna.getByLabel(/^Επαναλήψεις/).fill('10'); await dimitra.getByLabel(/^Βάρος/).fill('6'); await dimitra.getByLabel(/^Επαναλήψεις/).fill('12')
  await expect(feedback).toHaveText('Έτοιμοι για καταγραφή.')
  await bar.getByRole('button', { name: 'Καταγραφή και των δύο', exact: true }).click()
  await expect(feedback).toHaveText('Έτοιμοι για διάλειμμα.')
  await expect(bar.getByRole('button', { name: 'Έναρξη διαλείμματος', exact: true })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.screenshot({ path: info.outputPath('clean-action-bar.png'), fullPage: true })
  for (const control of await bar.locator('.workout-navigation').getByRole('button').all()) {
    const size = (await control.boundingBox())!
    expect(size.width).toBeGreaterThanOrEqual(44); expect(size.height).toBeGreaterThanOrEqual(44)
  }
  await bar.getByRole('button', { name: 'Έναρξη διαλείμματος', exact: true }).click()
  const rest = page.getByRole('dialog', { name: 'Διάλειμμα προπόνησης', exact: true })
  await expect(rest.getByRole('timer')).toHaveText(/00:(5\d|60)/)
  await rest.getByRole('button', { name: 'Πίσω στην καταγραφή', exact: true }).click()
  await expect(feedback).toHaveText('Διάλειμμα σε εξέλιξη.')
  await expect(bar.getByRole('button', { name: 'Άνοιγμα χρονομέτρου', exact: true })).toContainText(/00:/)
  await bar.getByRole('button', { name: 'Επόμενος γύρος', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Γύρος 2 / 3', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('action bar handles one present athlete and timed values without prompting for an absent athlete', async ({ page }) => {
  const { workout } = await mockAccount(page, 'coach', true, { active: true, routine: 2, configureWorkout: w => { w.results = {}; w.participants = ['anna'] } })
  await page.goto(`/#/workout/${workout.id}`)
  const bar = page.getByTestId('workout-controls'), feedback = bar.getByRole('status'), anna = page.getByTestId('panel-anna')
  await expect(feedback).toHaveText('Άννα: συμπληρώστε βάρος')
  await anna.getByLabel(/^Βάρος/).fill('5'); await expect(feedback).toHaveText('Άννα: συμπληρώστε διάρκεια')
  await anna.getByLabel(/^Διάρκεια/).fill('40')
  await expect(feedback).toHaveText('Άννα: πατήστε Καταγραφή.')
  await expect(bar.getByRole('button', { name: 'Αλλαγή ασκήσεων', exact: true })).toBeDisabled()
  await anna.getByRole('button', { name: 'Καταγραφή', exact: true }).click()
  await expect(feedback).toHaveText('Έτοιμοι για αλλαγή ασκήσεων.')
  await bar.getByRole('button', { name: 'Αλλαγή ασκήσεων', exact: true }).click()
  await expect(feedback).toHaveText('Άννα: συμπληρώστε διάρκεια')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('action bar identifies the pending TRX movement and keeps existing recordings intact', async ({ page }) => {
  const { workout } = await mockAccount(page, 'coach', true, { active: true, routine: 1, configureWorkout: w => { w.results = {}; w.stationIndex = 2 } })
  await page.goto(`/#/workout/${workout.id}`)
  const bar = page.getByTestId('workout-controls'), feedback = bar.getByRole('status'), anna = page.getByTestId('panel-anna'), dimitra = page.getByTestId('panel-dimitra')
  await expect(feedback).toContainText('Δήμητρα · TRX Biceps Curls: συμπληρώστε επαναλήψεις')
  const curls = dimitra.locator('form').filter({ has: page.getByRole('heading', { name: 'TRX Biceps Curls', exact: true }) })
  await curls.getByRole('button', { name: 'Παράλειψη', exact: true }).click()
  await expect(feedback).toContainText('Δήμητρα · TRX Triceps Extensions: συμπληρώστε επαναλήψεις')
  await anna.getByLabel(/^Βάρος/).fill('6'); await anna.getByLabel(/^Επαναλήψεις/).fill('10')
  await dimitra.locator('form').filter({ has: page.getByRole('heading', { name: 'TRX Triceps Extensions', exact: true }) }).getByLabel(/^Επαναλήψεις/).fill('11')
  await bar.getByRole('button', { name: 'Καταγραφή και αλλαγή', exact: true }).click()
  await bar.getByRole('button', { name: 'Πίσω', exact: true }).click()
  await expect(curls.getByText('Παράλειψη', { exact: true })).toBeVisible()
  await expect(feedback).toHaveText('Έτοιμοι για αλλαγή ασκήσεων.')
})
