import { test, expect } from '@playwright/test'
import { mockAccount } from './fixtures/cloud'

test('compact header keeps round flow and exits available, with keyboard-accessible confirmed actions', async ({ page }, testInfo) => {
  const { workout, requests } = await mockAccount(page, 'coach', true, { active: true })
  await page.goto(`/#/workout/${workout.id}`)
  await page.getByRole('button', { name: 'Λειτουργία προπόνησης', exact: true }).click()
  const header = page.getByTestId('round-header'), options = header.getByRole('button', { name: 'Επιλογές προπόνησης', exact: true })
  await expect(header.getByText('Σταθμός Α', { exact: true })).toBeVisible()
  await expect(header.getByRole('heading', { name: 'Γύρος 1 / 3', exact: true })).toBeVisible()
  await expect(header.getByRole('list', { name: 'Ροή γύρου' })).toBeVisible()
  await expect(page.getByRole('menu')).toHaveCount(0)
  await options.focus(); await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: 'Ολοκλήρωση', exact: true })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: 'Διακοπή', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('menu')).toHaveCount(0); await expect(options).toBeFocused()
  await options.click(); await page.getByRole('menuitem', { name: 'Ολοκλήρωση', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Ολοκλήρωση προπόνησης', exact: true })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Συνέχεια προπόνησης', exact: true }).click()
  await options.click(); await page.getByRole('menuitem', { name: 'Διακοπή', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Διακοπή χωρίς αποθήκευση', exact: true })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Ακύρωση', exact: true }).click()
  await options.click(); await header.getByRole('heading').click()
  await expect(page.getByRole('menu')).toHaveCount(0)
  const station = (await header.getByText('Σταθμός Α', { exact: true }).boundingBox())!, round = (await header.getByRole('heading').boundingBox())!
  if (page.viewportSize()!.width >= 680) expect(Math.abs(station.y - round.y)).toBeLessThan(10)
  await page.screenshot({ path: testInfo.outputPath('compact-header.png') })
  await page.getByRole('button', { name: 'Έξοδος από λειτουργία προπόνησης', exact: true }).click()
  await expect(page.locator('.topbar')).toBeVisible()
  expect(requests.filter(r => r.endpoint === 'save_record' || r.endpoint === 'delete_record')).toHaveLength(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
