import { clickAdjustment } from './fixtures/adjustments'
import { test, expect } from '@playwright/test'
import { normalPreview } from './fixtures/training'
import { mockAccount, synchronize } from './fixtures/cloud'

test('coach confirms offline weigh-in deletion, individual set deletion, and whole workout deletion', async ({ page, context }) => {
  const { requests, remote, workout } = await mockAccount(page, 'coach')
  await page.goto('/#/progress')
  await expect(page.locator('.weighin-table tbody tr')).toHaveCount(2)
  const deleteWeight = page.getByRole('button', { name: 'Διαγραφή μέτρησης Άννα 2026-10-01', exact: true })
  await expect(deleteWeight).toBeEnabled()
  await deleteWeight.click()
  await page.getByRole('dialog').getByRole('button', { name: 'Ακύρωση', exact: true }).click()
  await expect(page.locator('.weighin-table tbody tr')).toHaveCount(2)
  await context.setOffline(true)
  await deleteWeight.click()
  await page.getByRole('dialog').getByRole('button', { name: 'Διαγραφή', exact: true }).click()
  await expect(page.locator('.weighin-table tbody tr')).toHaveCount(1)
  await expect(page.locator('.weight-card.anna .current-weight')).toContainText('—')
  await expect(page.locator('.weight-card.dimitra .current-weight')).toContainText('101')
  expect(requests).toHaveLength(0)
  await context.setOffline(false); await synchronize(page)
  await expect.poll(() => requests.filter(r => r.endpoint === 'delete_record' && r.kind === 'weighin').length).toBe(1)
  await page.goto(`/#/history?session=${workout.id}`)
  await expect(page.getByText('6,25 kg / αλτήρα · 10 επ.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Διαγραφή σετ Άννα Goblet Squats σετ 1', exact: true }).click()
  const confirmation = page.getByRole('dialog', { name: 'Διαγραφή καταγεγραμμένου σετ', exact: true })
  await confirmation.getByRole('button', { name: 'Διαγραφή', exact: true }).click()
  await expect(page.locator('.result-history-row')).toHaveCount(43)
  await expect(page.locator('.history-athlete.anna').getByText('6,25 kg / αλτήρα · 10 επ.', { exact: true })).toHaveCount(0)
  await expect(page.locator('.history-athlete.dimitra').getByText('10 επ.', { exact: true })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: 'Κλείσιμο', exact: true }).click()
  await synchronize(page)
  expect(requests.some(r => r.endpoint === 'save_record' && r.kind === 'workout')).toBe(true)
  await page.goto(`/#/history?session=${workout.id}`)
  await expect(page.locator('.result-history-row')).toHaveCount(43)
  await page.getByRole('button', { name: 'Διαγραφή προπόνησης', exact: true }).click()
  await page.getByRole('dialog', { name: 'Διαγραφή προπόνησης', exact: true }).getByRole('button', { name: 'Διαγραφή', exact: true }).click()
  await expect(page.getByText('Το ιστορικό σας ξεκινά εδώ.', { exact: true })).toBeVisible()
  await synchronize(page)
  expect(requests.some(r => r.endpoint === 'delete_record' && r.kind === 'workout')).toBe(true)
  expect(remote.workouts).toEqual([]); expect(remote.notes).toEqual([])
  await page.goto('/#/history'); await page.reload()
  await expect(page.getByText('Το ιστορικό σας ξεκινά εδώ.', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
test('athletes cannot access deletion controls, and old databases keep coach deletion disabled', async ({ page }) => {
  const { workout } = await mockAccount(page, 'athlete')
  await page.goto('/#/progress')
  await expect(page.locator('.weighin-table tbody tr')).toHaveCount(2)
  await expect(page.getByRole('button', { name: /^Διαγραφή/ })).toHaveCount(0)
  await page.goto(`/#/history?session=${workout.id}`)
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('button', { name: /^Διαγραφή/ })).toHaveCount(0)
  await expect(page.getByRole('button', { name: /^Επεξεργασία προπόνησης|^Διόρθωση/ })).toHaveCount(0)
  const coach = await page.context().newPage()
  try {
    const legacy = await mockAccount(coach, 'coach', false, { active: true, workoutDiscard: false })
    await coach.goto('/#/progress')
    await expect(coach.getByRole('button', { name: 'Διαγραφή μέτρησης Άννα 2026-10-01', exact: true })).toBeDisabled()
    await expect(coach.getByText('Η διαγραφή ιστορικού θα είναι διαθέσιμη μόλις ενεργοποιηθεί για την ομάδα.')).toBeVisible()
    await coach.goto(`/#/workout/${legacy.workout.id}`)
    await coach.getByRole('button', { name: 'Επιλογές προπόνησης', exact: true }).click()
    await expect(coach.getByRole('menuitem', { name: 'Διακοπή', exact: true })).toBeDisabled()
    await coach.goto('/#/')
    await coach.getByRole('button', { name: 'Έναρξη Προπόνηση 2', exact: true }).click()
    await expect(coach.getByRole('button', { name: 'Διακοπή και νέα προπόνηση', exact: true })).toBeDisabled()
  } finally { await coach.close() }
})
test('weight buttons adjust exact quarter-kilogram loads independently and respect recorded sets and limits', async ({ page }, info) => {
  await normalPreview(page)
  await page.goto('/')
  await page.getByRole('button', { name: 'Προεπισκόπηση στη συσκευή' }).click()
  await page.getByRole('button', { name: 'Ξεκινήστε προπόνηση' }).click()
  await page.getByRole('button', { name: 'Έναρξη προπόνησης', exact: true }).click()
  const anna = page.getByTestId('panel-anna'), dimitra = page.getByTestId('panel-dimitra')
  await expect(dimitra.locator('.weight-increments')).toHaveCount(0)
  const weight = anna.getByLabel(/^Βάρος/), controls = anna.locator('.weight-increments')
  const plus = controls.getByRole('button', { name: /^Αύξηση/ }), minus = controls.getByRole('button', { name: /^Μείωση/ }), step = controls.getByRole('combobox')
  await expect(step).toHaveValue('1.25'); await expect(plus).toHaveText('+'); await expect(minus).toHaveText('−')
  await expect(step.locator('option')).toHaveText(['1,25', '2,5'])
  await step.selectOption('2.5'); await weight.fill('497.5'); await plus.click()
  await expect(weight).toHaveValue('500'); await expect(plus).toBeDisabled()
  await minus.click(); await expect(weight).toHaveValue('497.5')
  await weight.fill(''); await expect(minus).toBeDisabled()
  await step.selectOption('1.25'); await expect(minus).toBeDisabled(); await plus.click({ clickCount: 2 })
  await step.selectOption('2.5'); await plus.click(); await expect(weight).toHaveValue('5')
  await minus.click(); await expect(weight).toHaveValue('2.5')
  await step.selectOption('1.25'); await minus.click({ clickCount: 2 }); await expect(weight).toHaveValue('0')
  await expect(minus).toBeDisabled(); await step.selectOption('2.5'); await expect(minus).toBeDisabled()
  await weight.fill('2.4'); await expect(minus).toBeDisabled()
  await step.selectOption('1.25'); await minus.click(); await expect(weight).toHaveValue('1.15')
  await weight.fill('5')
  for (const control of [plus, minus, step]) {
    const size = await control.boundingBox(); expect(size!.height).toBeGreaterThanOrEqual(44); expect(size!.width).toBeGreaterThanOrEqual(44)
  }
  await page.screenshot({ path: `test-results/weight-controls-${info.project.name}.png`, fullPage: true })
  await anna.getByLabel(/^Επαναλήψεις/).fill('10')
  await anna.getByRole('button', { name: 'Καταγραφή', exact: true }).click()
  await expect(plus).toBeDisabled(); await expect(minus).toBeDisabled(); await expect(step).toBeDisabled()
  await dimitra.getByLabel(/^Επαναλήψεις/).fill('11')
  await dimitra.getByRole('button', { name: 'Καταγραφή', exact: true }).click()
  await page.getByRole('button', { name: 'Αλλαγή ασκήσεων', exact: true }).click()
  await clickAdjustment(dimitra, 'Αύξηση 2.5 kg Δήμητρα Goblet Squats')
  await clickAdjustment(dimitra, 'Αύξηση 1.25 kg Δήμητρα Goblet Squats')
  await expect(dimitra.getByLabel(/^Βάρος/)).toHaveValue('3.75')
  await clickAdjustment(dimitra, 'Μείωση 1.25 kg Δήμητρα Goblet Squats')
  await expect(dimitra.getByLabel(/^Βάρος/)).toHaveValue('2.5')
  await page.reload()
  await expect(dimitra.getByLabel(/^Βάρος/)).toHaveValue('2.5')
  await expect(dimitra.locator('.weight-increments').getByRole('combobox')).toHaveValue('1.25')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
