import { clickAdjustment } from './fixtures/adjustments'
import { test, expect, type Page } from '@playwright/test'
import { mockAccount, synchronize } from './fixtures/cloud'
import { requiredResults } from '../../src/lib/model'

async function start(page: Page, routine = 1) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Προεπισκόπηση στη συσκευή', exact: true }).click()
  await page.getByRole('button', { name: `Έναρξη Προπόνηση ${routine}`, exact: true }).click()
  await page.getByRole('button', { name: 'Έναρξη προπόνησης', exact: true }).click()
  await expect(page.getByTestId('panel-anna')).toBeVisible()
}
async function fillPair(page: Page, values = ['10', '12'], weight = '6.25') {
  for (const [index, athlete] of ['anna', 'dimitra'].entries()) {
    const panel = page.getByTestId(`panel-${athlete}`)
    const load = panel.getByLabel(/^Βάρος/)
    if (await load.count()) await load.fill(weight)
    await panel.getByLabel(/^(Επαναλήψεις|Διάρκεια)/).fill(values[index])
  }
}
async function recordPairIndividually(page: Page) {
  for (const athlete of ['anna', 'dimitra']) await page.getByTestId(`panel-${athlete}`).getByRole('button', { name: 'Καταγραφή', exact: true }).click()
}

test('reuse fills separate athlete values without recording and survives reload, then uses saved history', async ({ page, context }) => {
  await start(page)
  const anna = page.getByTestId('panel-anna'), dimitra = page.getByTestId('panel-dimitra')
  await expect(anna.getByRole('button', { name: 'Ίδιο με πριν' })).toHaveCount(0)
  await fillPair(page); await recordPairIndividually(page)
  await page.getByRole('button', { name: 'Αλλαγή ασκήσεων', exact: true }).click()
  await expect(anna.getByRole('heading', { name: 'TRX Rows', exact: true })).toBeVisible()
  await fillPair(page, ['11', '9'], '8'); await recordPairIndividually(page)
  await page.getByRole('button', { name: 'Επόμενος γύρος', exact: true }).click()
  await anna.getByRole('button', { name: 'Ίδιο με πριν' }).click()
  await expect(anna.getByLabel(/^Βάρος/)).toHaveValue('6.25')
  await expect(anna.getByLabel(/^Επαναλήψεις/)).toHaveValue('10')
  await expect(dimitra.getByLabel(/^Επαναλήψεις/)).toHaveValue('')
  await expect(anna.getByText('Έγινε', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Αλλαγή ασκήσεων', exact: true })).toBeDisabled()
  await context.setOffline(true)
  await dimitra.getByRole('button', { name: 'Ίδιο με πριν' }).click()
  await expect(dimitra.getByLabel(/^Επαναλήψεις/)).toHaveValue('12')
  await context.setOffline(false); await page.reload()
  await expect(anna.getByLabel(/^Βάρος/)).toHaveValue('6.25')
  await expect(dimitra.getByLabel(/^Επαναλήψεις/)).toHaveValue('12')
  await clickAdjustment(anna, 'Αύξηση 1 επαναλήψεων Άννα Goblet Squats')
  await recordPairIndividually(page)
  await expect(anna.getByRole('button', { name: 'Ίδιο με πριν' })).toBeDisabled()
  await page.getByRole('button', { name: 'Επιλογές προπόνησης', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Ολοκλήρωση', exact: true }).click()
  await page.getByRole('button', { name: 'Αποθήκευση & τέλος', exact: true }).click()
  await expect(page).toHaveURL(/#\/history\?session=/)
  await expect(page.getByRole('dialog', { name: 'Προπόνηση 1', exact: true })).toBeVisible()
  await page.goto('/#/'); await page.getByRole('button', { name: 'Ξεκινήστε προπόνηση', exact: true }).click()
  await page.getByRole('button', { name: 'Έναρξη προπόνησης', exact: true }).click()
  await anna.getByRole('button', { name: 'Ίδιο με πριν' }).click()
  await dimitra.getByRole('button', { name: 'Ίδιο με πριν' }).click()
  await expect(anna.getByLabel(/^Επαναλήψεις/)).toHaveValue('11')
  await expect(dimitra.getByLabel(/^Επαναλήψεις/)).toHaveValue('12')
  await expect(anna).toContainText('Προηγούμενη προπόνηση')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('both recordings validate the entire pair, preserve individual entries and synchronize offline', async ({ page, context }) => {
  const { workout, requests, remote } = await mockAccount(page, 'coach', true, { active: true })
  await page.goto(`/#/workout/${workout.id}`)
  await page.getByRole('button', { name: 'Αλλαγή ασκήσεων', exact: true }).click()
  const anna = page.getByTestId('panel-anna'), dimitra = page.getByTestId('panel-dimitra'), both = page.getByRole('button', { name: 'Καταγραφή και των δύο', exact: true })
  await expect(anna.getByRole('heading', { name: 'TRX Rows', exact: true })).toBeVisible()
  await expect(both).toBeDisabled()
  await anna.getByLabel(/^Επαναλήψεις/).fill('9')
  await expect(both).toBeDisabled()
  await dimitra.getByLabel(/^Βάρος/).fill('7.5'); await dimitra.getByLabel(/^Επαναλήψεις/).fill('12')
  await expect(both).toBeEnabled()
  await anna.getByRole('button', { name: 'Καταγραφή', exact: true }).click()
  await expect(both).toBeEnabled()
  await context.setOffline(true); await both.click()
  await expect(anna.getByText('Έγινε', { exact: true })).toBeVisible()
  await expect(dimitra.getByText('Έγινε', { exact: true })).toBeVisible()
  await expect(both).toBeDisabled()
  await expect(page.getByRole('heading', { name: 'Γύρος 1 / 3' })).toBeVisible()
  expect(requests).toHaveLength(0)
  await context.setOffline(false); await synchronize(page)
  const saved = requests.filter(r => r.endpoint === 'save_record' && r.kind === 'workout')
  expect(saved).toHaveLength(1)
  expect(Object.values(remote.workouts[0].results).filter(r => r.status === 'completed')).toHaveLength(4)
  await page.goto(`/#/workout/${workout.id}`)
  await page.reload()
  await expect(anna.getByLabel(/^Επαναλήψεις/)).toHaveValue('9')
  await expect(dimitra.getByLabel(/^Βάρος/)).toHaveValue('7.5')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('record both includes every TRX movement before the swap', async ({ page }) => {
  const { workout } = await mockAccount(page, 'coach', true, { active: true, routine: 1 })
  workout.stationIndex = 2; workout.results = {}
  await page.goto(`/#/workout/${workout.id}`)
  const anna = page.getByTestId('panel-anna'), dimitra = page.getByTestId('panel-dimitra'), both = page.getByRole('button', { name: 'Καταγραφή και των δύο', exact: true })
  await anna.getByLabel(/^Βάρος/).fill('5'); await anna.getByLabel(/^Επαναλήψεις/).fill('10')
  const curls = dimitra.locator('form').filter({ has: page.getByRole('heading', { name: 'TRX Biceps Curls', exact: true }) })
  const triceps = dimitra.locator('form').filter({ has: page.getByRole('heading', { name: 'TRX Triceps Extensions', exact: true }) })
  await curls.getByLabel(/^Επαναλήψεις/).fill('9')
  await expect(both).toBeDisabled()
  await triceps.getByLabel(/^Επαναλήψεις/).fill('11'); await both.click()
  await expect(dimitra.getByText('Έγινε', { exact: true })).toHaveCount(2)
  await expect(page.getByRole('button', { name: 'Αλλαγή ασκήσεων', exact: true })).toBeEnabled()
})

test('rest is manually started, pauses and recovers without advancing, then Continue advances once', async ({ page }, info) => {
  await start(page, 3)
  await page.getByRole('button', { name: 'Άνοιγμα χρονομέτρου', exact: true }).click()
  await page.getByRole('button', { name: 'Άσκηση', exact: true }).click()
  await page.getByRole('button', { name: 'Έναρξη και για τις δύο', exact: true }).click()
  await page.getByRole('button', { name: 'Κλείσιμο', exact: true }).click()
  await fillPair(page, ['36', '38']); await page.getByRole('button', { name: 'Καταγραφή και των δύο', exact: true }).click()
  await page.getByRole('button', { name: 'Αλλαγή ασκήσεων', exact: true }).click()
  const anna = page.getByTestId('panel-anna')
  await expect(anna.getByRole('heading', { name: 'TRX Y-Fly', exact: true })).toBeVisible()
  await fillPair(page, ['37', '35']); await page.getByRole('button', { name: 'Καταγραφή και των δύο', exact: true }).click()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('wl-timers:local:local') || '[]').filter((j: { id: string }) => j.id === 'rest'))).toEqual([])
  await page.getByRole('button', { name: 'Έναρξη διαλείμματος', exact: true }).click()
  const rest = page.getByRole('dialog', { name: 'Διάλειμμα προπόνησης', exact: true }), clock = rest.getByRole('timer', { name: 'Χρόνος διαλείμματος', exact: true })
  await expect(clock).toContainText(/00:(19|20)/)
  await expect(rest).toContainText('Σταθμός Α · Γύρος 2 / 3')
  await expect(rest.locator('.rest-athlete.anna')).toContainText('Dumbbell Thrusters')
  await expect(rest.locator('.rest-athlete.dimitra')).toContainText('TRX Y-Fly')
  expect(await rest.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  const continueBox = await rest.getByRole('button', { name: 'Συνέχεια', exact: true }).boundingBox()
  expect(continueBox!.y + continueBox!.height).toBeLessThanOrEqual(page.viewportSize()!.height)
  await page.screenshot({ path: `test-results/rest-view-${info.project.name}.png` })
  await rest.getByRole('button', { name: 'Παύση διαλείμματος', exact: true }).click()
  await expect(rest).toContainText('ΣΕ ΠΑΥΣΗ')
  await page.reload()
  await expect(rest).toBeVisible(); await expect(rest).toContainText('ΣΕ ΠΑΥΣΗ')
  await rest.getByRole('button', { name: 'Συνέχιση διαλείμματος', exact: true }).click()
  await expect(rest).toContainText('ΧΡΟΝΟΣ ΔΙΑΛΕΙΜΜΑΤΟΣ')
  await rest.getByRole('button', { name: 'Επαναφορά διαλείμματος', exact: true }).click()
  await expect(clock).toHaveText('00:20'); await expect(rest).toContainText('ΣΕ ΠΑΥΣΗ')
  await rest.getByLabel('Διάρκεια διαλείμματος σε δευτερόλεπτα', { exact: true }).fill('1')
  await rest.getByRole('button', { name: 'Επανεκκίνηση', exact: true }).click()
  await expect(clock).toHaveText('00:00')
  await expect(rest.getByRole('status')).toContainText('Το διάλειμμα ολοκληρώθηκε')
  await rest.getByRole('button', { name: 'Κλείσιμο', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Γύρος 1 / 3' })).toBeVisible()
  await page.getByRole('button', { name: 'Προβολή διαλείμματος', exact: true }).click()
  await expect(clock).toHaveText('00:00')
  await rest.getByRole('button', { name: 'Συνέχεια', exact: true }).click({ clickCount: 2 })
  await expect(rest).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Γύρος 2 / 3' })).toBeVisible()
  await expect(anna.getByLabel(/^Διάρκεια/)).toHaveValue('')
  await anna.getByRole('button', { name: 'Ίδιο με πριν' }).click()
  await expect(anna.getByLabel(/^Διάρκεια/)).toHaveValue('36')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('wl-timers:local:local') || '[]').map((j: { id: string }) => j.id))).toHaveLength(2)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('minimal rest has no preset and final Continue requires explicit workout saving', async ({ page }) => {
  const { workout } = await mockAccount(page, 'coach', true, { active: true })
  workout.stationIndex = 3; workout.phase = 1; workout.results = {}
  for (const r of requiredResults(workout)) workout.results[r.key] = { ...r, status: 'completed', value: r.movement.metric === 'seconds' ? 40 : 15, weight: r.movement.loaded ? 6 : null }
  await page.goto(`/#/workout/${workout.id}`)
  await page.getByRole('button', { name: 'Διάλειμμα', exact: true }).click()
  const rest = page.getByRole('dialog', { name: 'Διάλειμμα προπόνησης', exact: true })
  await expect(rest.getByRole('timer')).toHaveText('—')
  await expect(rest.getByLabel('Διάρκεια διαλείμματος σε δευτερόλεπτα', { exact: true })).toHaveValue('')
  await expect(rest.getByRole('button', { name: 'Έναρξη', exact: true })).toBeDisabled()
  await rest.getByRole('button', { name: '30″', exact: true }).click()
  await expect(rest.getByRole('timer')).toHaveText('—')
  await rest.getByRole('button', { name: 'Συνέχεια', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Γύρος 2 / 2' })).toBeVisible()
  await fillPair(page, ['15', '40'], '6'); await page.getByRole('button', { name: 'Καταγραφή και των δύο', exact: true }).click()
  await page.getByRole('button', { name: 'Αλλαγή ασκήσεων', exact: true }).click()
  await expect(page.getByTestId('panel-anna').getByRole('heading', { name: 'Plank', exact: true })).toBeVisible()
  await fillPair(page, ['38', '15'], '6'); await page.getByRole('button', { name: 'Καταγραφή και των δύο', exact: true }).click()
  await page.getByRole('button', { name: 'Διάλειμμα', exact: true }).click()
  await expect(rest).toContainText('Ολοκληρώθηκε ο τελευταίος γύρος')
  await expect(rest.locator('.rest-athlete')).toHaveCount(0)
  await rest.getByRole('button', { name: 'Συνέχεια', exact: true }).click()
  const finish = page.getByRole('dialog', { name: 'Ολοκλήρωση προπόνησης', exact: true })
  await expect(finish).toBeVisible(); await expect(page).toHaveURL(/#\/workout\//)
  await finish.getByRole('button', { name: 'Αποθήκευση & τέλος', exact: true }).click()
  await expect(page).toHaveURL(/#\/history\?session=/)
})

test('rest previews the next station and supports a single present athlete', async ({ page }) => {
  const { workout } = await mockAccount(page, 'coach', true, { active: true })
  workout.roundIndex = 2; workout.phase = 1; workout.participants = ['anna']; workout.results = {}
  for (const r of requiredResults(workout)) workout.results[r.key] = { ...r, status: 'completed', value: 10, weight: r.movement.loaded ? 6 : null }
  await page.goto(`/#/workout/${workout.id}`)
  await expect(page.getByRole('button', { name: 'Καταγραφή και των δύο', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Έναρξη διαλείμματος', exact: true }).click()
  const rest = page.getByRole('dialog', { name: 'Διάλειμμα προπόνησης', exact: true })
  await expect(rest).toContainText('Σταθμός Β · Γύρος 1 / 3')
  await expect(rest.locator('.rest-athlete')).toHaveCount(1)
  await expect(rest).toContainText('Bench Press')
  await rest.getByRole('button', { name: 'Συνέχεια', exact: true }).click()
  await expect(page.getByTestId('panel-anna').getByRole('heading', { name: 'Bench Press', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Γύρος 1 / 3' })).toBeVisible()
})
