import { test, expect } from '@playwright/test'
import { createWorkout } from '../../src/lib/model'
import { mockAccount, synchronize } from './fixtures/cloud'

test('four-step flow and combined save/swap survive reload and synchronize as one workout', async ({ page, context }) => {
  const { workout, requests, remote } = await mockAccount(page, 'coach', true, { active: true, configureWorkout: w => { w.results = {} } })
  await page.goto(`/#/workout/${workout.id}`)
  const flow = page.getByRole('list', { name: 'Ροή γύρου' }), anna = page.getByTestId('panel-anna'), dimitra = page.getByTestId('panel-dimitra')
  await expect(flow.locator('[aria-current="step"]')).toHaveAttribute('data-step', '0')
  await expect(page.getByRole('button', { name: 'Αλλαγή ασκήσεων', exact: true })).toBeDisabled()
  await anna.getByLabel(/^Βάρος/).fill('6.25'); await anna.getByLabel(/^Επαναλήψεις/).fill('11')
  await dimitra.getByLabel(/^Επαναλήψεις/).fill('9')
  const combined = page.getByRole('button', { name: 'Καταγραφή και αλλαγή', exact: true })
  await expect(combined).toBeEnabled()
  await context.setOffline(true); await combined.click({ clickCount: 2 })
  await expect(anna.getByRole('heading', { name: 'TRX Rows', exact: true })).toBeVisible()
  await expect(flow.locator('[aria-current="step"]')).toHaveAttribute('data-step', '2')
  await expect(page.getByRole('heading', { name: 'Γύρος 1 / 3' })).toBeVisible()
  await context.setOffline(false); await page.reload()
  await expect(flow.locator('[aria-current="step"]')).toHaveAttribute('data-step', '2')
  await synchronize(page)
  const operations = requests.filter(r => r.endpoint === 'save_record' && r.kind === 'workout').map(r => (r as typeof r & { operation_id: string }).operation_id)
  expect(operations.length).toBeGreaterThan(0)
  expect(new Set(operations).size).toBe(1) // Reloads may retry the same idempotent operation.
  expect(remote.workouts[0].phase).toBe(1)
  expect(Object.values(remote.workouts[0].results).filter(r => r.status === 'completed')).toHaveLength(2)
  await page.goto(`/#/workout/${workout.id}`)
  await anna.getByLabel(/^Επαναλήψεις/).fill('12'); await dimitra.getByLabel(/^Βάρος/).fill('7.5'); await dimitra.getByLabel(/^Επαναλήψεις/).fill('10')
  await page.getByRole('button', { name: 'Καταγραφή και των δύο', exact: true }).click()
  await expect(flow.locator('[aria-current="step"]')).toHaveAttribute('data-step', '3')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('wl-timers:20000000-0000-0000-0000-000000000001:10000000-0000-0000-0000-000000000001') || '[]'))).toEqual([])
  await page.getByRole('button', { name: 'Πίσω', exact: true }).click()
  await expect(flow.locator('[aria-current="step"]')).toHaveAttribute('data-step', '1')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('quick choices follow focus, use own recent loads, and fill editable actuals', async ({ page }) => {
  const { remote, workout: history } = await mockAccount(page, 'coach')
  const active = createWorkout(remote.program.routines[0], remote.program.id)
  remote.workouts.unshift(active)
  const other = Object.values(history.results).find(r => r.athlete === 'dimitra' && r.movement.id === 'goblet')!
  other.status = 'completed'; other.value = 12; other.weight = 11.25
  await page.goto(`/#/workout/${active.id}`)
  const anna = page.getByTestId('panel-anna'), dimitra = page.getByTestId('panel-dimitra')
  await expect(page.locator('.quick-choices')).toHaveCount(0)
  await anna.getByLabel(/^Βάρος/).focus()
  await expect(page.locator('.quick-choices')).toHaveCount(1)
  await expect(anna.getByRole('button', { name: 'Χρήση 6,25 kg Άννα Goblet Squats βάρος', exact: true })).toBeVisible()
  await expect(anna.getByRole('button', { name: /Χρήση 11,25 kg/ })).toHaveCount(0)
  await anna.getByRole('button', { name: 'Χρήση 6,25 kg Άννα Goblet Squats βάρος', exact: true }).click()
  await expect(anna.getByLabel(/^Βάρος/)).toHaveValue('6.25')
  await anna.getByLabel(/^Επαναλήψεις/).focus()
  await expect(page.getByRole('button', { name: /Χρήση 6,25 kg/ })).toHaveCount(0)
  for (const value of ['10', '11', '12']) await expect(anna.getByRole('button', { name: `Χρήση ${value} επ. Άννα Goblet Squats επαναλήψεις`, exact: true })).toBeVisible()
  await anna.getByRole('button', { name: 'Χρήση 11 επ. Άννα Goblet Squats επαναλήψεις', exact: true }).click()
  await expect(anna.getByLabel(/^Επαναλήψεις/)).toHaveValue('11')
  await expect(anna.getByText('Έγινε', { exact: true })).toHaveCount(0)
  await expect(dimitra.getByLabel(/^Επαναλήψεις/)).toHaveValue('')
  await dimitra.getByLabel(/^Επαναλήψεις/).focus()
  await expect(anna.locator('.quick-choices')).toHaveCount(0)
  await expect(dimitra.locator('.quick-choices')).toHaveCount(1)
  await dimitra.getByRole('button', { name: 'Χρήση 12 επ. Δήμητρα TRX Rows επαναλήψεις', exact: true }).click()
  await anna.getByRole('button', { name: 'Καταγραφή', exact: true }).click()
  await expect(anna.locator('.quick-choices')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('timed quick choices keep timers and the other athlete independent', async ({ page }) => {
  const { workout } = await mockAccount(page, 'coach', true, { active: true, routine: 2, configureWorkout: w => { w.results = {} } })
  await page.goto(`/#/workout/${workout.id}`)
  const anna = page.getByTestId('panel-anna'), dimitra = page.getByTestId('panel-dimitra')
  await anna.getByLabel(/^Διάρκεια/).focus()
  await anna.getByRole('button', { name: 'Χρήση 40 δευτ. Άννα Dumbbell Thrusters διάρκεια', exact: true }).click()
  await expect(anna.getByLabel(/^Διάρκεια/)).toHaveValue('40')
  await expect(dimitra.getByLabel(/^Διάρκεια/)).toHaveValue('')
  await page.getByRole('button', { name: 'Άνοιγμα χρονομέτρου', exact: true }).click()
  await expect(page.locator('.timer-job')).toHaveCount(0)
  await page.getByRole('button', { name: 'Κλείσιμο', exact: true }).click()
})

test('unilateral quick choices fill the optional side independently', async ({ page }) => {
  const { workout } = await mockAccount(page, 'coach', true, { active: true, configureWorkout: w => { w.stationIndex = 2; w.results = {} } })
  await page.goto(`/#/workout/${workout.id}`)
  const anna = page.getByTestId('panel-anna')
  await anna.getByLabel(/^Επαναλήψεις/).fill('11')
  await anna.getByLabel(/^Άλλη πλευρά/).focus()
  await anna.getByRole('button', { name: 'Χρήση 10 επ. Άννα Split Squats άλλη πλευρά', exact: true }).click()
  await expect(anna.getByLabel(/^Άλλη πλευρά/)).toHaveValue('10')
  await expect(anna.getByLabel(/^Επαναλήψεις/)).toHaveValue('11')
})

test('training mode keeps the round and action visible, persists, and restores navigation', async ({ page }, testInfo) => {
  const { workout, requests } = await mockAccount(page, 'coach', true, { active: true })
  await page.goto(`/#/workout/${workout.id}`)
  await page.getByRole('button', { name: 'Σκοτεινό θέμα', exact: true }).click()
  await page.getByRole('button', { name: 'Λειτουργία προπόνησης', exact: true }).click()
  const exit = page.getByRole('button', { name: 'Έξοδος από λειτουργία προπόνησης', exact: true })
  await expect(exit).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.sidebar')).toBeHidden()
  await expect(page.locator('.bottom-nav')).toBeHidden()
  await expect(page.locator('.topbar')).toBeHidden()
  await expect(page.getByTestId('panel-anna')).toBeVisible()
  await expect(page.getByTestId('panel-dimitra')).toBeVisible()
  await expect(page.getByTestId('workout-controls').getByText('Συγχρονισμένο', { exact: true })).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight))
  const header = (await page.getByTestId('round-header').boundingBox())!, footer = (await page.getByTestId('workout-controls').boundingBox())!
  expect(header.y).toBeGreaterThanOrEqual(0); expect(header.y).toBeLessThan(40)
  expect(footer.y + footer.height).toBeLessThanOrEqual(page.viewportSize()!.height + 1)
  await expect(exit).toBeInViewport()
  await expect(page.getByRole('button', { name: 'Αλλαγή ασκήσεων', exact: true })).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('training-mode-dark.png') })
  await page.reload()
  await expect(exit).toBeVisible()
  await expect(page.getByRole('list', { name: 'Ροή γύρου' }).locator('[aria-current="step"]')).toHaveAttribute('data-step', '1')
  await page.goto('/#/progress')
  await expect(page.locator('.topbar')).toBeVisible()
  await expect(page.locator('.training-mode')).toHaveCount(0)
  await page.goto(`/#/workout/${workout.id}`)
  await expect(exit).toBeVisible()
  await exit.click()
  await expect(page.locator('.topbar')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Λειτουργία προπόνησης', exact: true })).toBeVisible()
  expect(requests.filter(r => r.endpoint === 'save_record')).toHaveLength(0)
})

test('training mode records and swaps, opens a manual rest, and permits discarding the session', async ({ page }, testInfo) => {
  const { workout } = await mockAccount(page, 'coach', true, { active: true, configureWorkout: w => { w.results = {} } })
  await page.goto(`/#/workout/${workout.id}`)
  await page.getByRole('button', { name: 'Λειτουργία προπόνησης', exact: true }).click()
  const anna = page.getByTestId('panel-anna'), dimitra = page.getByTestId('panel-dimitra'), controls = page.getByTestId('workout-controls')
  await anna.getByLabel(/^Βάρος/).fill('5'); await anna.getByLabel(/^Επαναλήψεις/).focus()
  await anna.getByRole('button', { name: 'Χρήση 11 επ. Άννα Goblet Squats επαναλήψεις', exact: true }).click()
  await dimitra.getByLabel(/^Επαναλήψεις/).fill('12')
  await controls.getByRole('button', { name: 'Καταγραφή και αλλαγή', exact: true }).click()
  await expect(anna.getByRole('heading', { name: 'TRX Rows', exact: true })).toBeVisible()
  await anna.getByLabel(/^Επαναλήψεις/).fill('10'); await dimitra.getByLabel(/^Βάρος/).fill('7.5'); await dimitra.getByLabel(/^Επαναλήψεις/).fill('12')
  await controls.getByRole('button', { name: 'Καταγραφή και των δύο', exact: true }).click()
  await expect(controls.getByRole('button', { name: 'Έναρξη διαλείμματος', exact: true })).toBeEnabled()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('training-mode-light.png') })
  await controls.getByRole('button', { name: 'Έναρξη διαλείμματος', exact: true }).click()
  const rest = page.getByRole('dialog', { name: 'Διάλειμμα προπόνησης' })
  await expect(rest).toBeVisible()
  await rest.getByRole('button', { name: 'Παύση διαλείμματος', exact: true }).click()
  await rest.getByRole('button', { name: 'Συνέχεια', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Γύρος 2 / 3', exact: true })).toBeVisible()
  await expect(page.getByRole('list', { name: 'Ροή γύρου' }).locator('[aria-current="step"]')).toHaveAttribute('data-step', '0')
  await page.getByRole('button', { name: 'Διακοπή', exact: true }).click()
  const discard = page.getByRole('dialog')
  await discard.getByRole('button', { name: 'Διακοπή χωρίς αποθήκευση', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Καλώς ήρθατε στο Lab.' })).toBeVisible()
  await expect(page.locator('.topbar')).toBeVisible()
  await expect(page.locator('.training-mode')).toHaveCount(0)
})

test('training mode supports one present athlete and restores navigation after saving', async ({ page }) => {
  const { workout } = await mockAccount(page, 'coach', true, { active: true, configureWorkout: w => { w.results = {}; w.participants = ['anna'] } })
  await page.goto(`/#/workout/${workout.id}`)
  await page.getByRole('button', { name: 'Λειτουργία προπόνησης', exact: true }).click()
  const anna = page.getByTestId('panel-anna')
  await expect(page.getByTestId('panel-dimitra').getByRole('heading', { name: 'Απούσα', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Καταγραφή και των δύο', exact: true })).toHaveCount(0)
  await anna.getByLabel(/^Βάρος/).fill('5'); await anna.getByLabel(/^Επαναλήψεις/).fill('10')
  await anna.getByRole('button', { name: 'Καταγραφή', exact: true }).click()
  await page.getByRole('button', { name: 'Αλλαγή ασκήσεων', exact: true }).click()
  await anna.getByLabel(/^Επαναλήψεις/).fill('12')
  await anna.getByRole('button', { name: 'Καταγραφή', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Έναρξη διαλείμματος', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Ολοκλήρωση', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'Αποθήκευση & τέλος', exact: true }).click()
  await expect(page.locator('.topbar')).toBeVisible()
  await expect(page.locator('.training-mode')).toHaveCount(0)
  const saved = page.getByRole('dialog', { name: 'Προπόνηση 1', exact: true })
  await expect(saved).toContainText('5 kg / αλτήρα · 10 επ.')
  await expect(saved).toContainText('12 επ.')
  await saved.getByRole('button', { name: 'Κλείσιμο', exact: true }).click()
  await expect(page.getByRole('heading', { name: /^Ιστορικό προπονήσεων/ })).toBeVisible()
})
