import { clickAdjustment } from './fixtures/adjustments'
import { test, expect, type Page } from '@playwright/test'
import { mockAccount, synchronize } from './fixtures/cloud'

async function preview(page: Page, routine = 1) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Προεπισκόπηση στη συσκευή' }).click()
  await page.getByRole('button', { name: `Έναρξη Προπόνηση ${routine}`, exact: true }).click()
  await page.getByRole('button', { name: 'Έναρξη προπόνησης', exact: true }).click()
  await expect(page.getByTestId('panel-anna')).toBeVisible()
}

test('coach edits saved dates and both athletes offline, cancels drafts, and syncs the corrected history', async ({ page, context }, info) => {
  const { requests, remote, workout } = await mockAccount(page, 'coach')
  await page.goto(`/#/history?session=${workout.id}`)
  await page.getByRole('button', { name: 'Επεξεργασία προπόνησης', exact: true }).click()
  let editor = page.getByRole('dialog', { name: 'Επεξεργασία προπόνησης', exact: true })
  await editor.getByLabel('Ημερομηνία προπόνησης', { exact: true }).fill('2026-10-01')
  let set = editor.getByRole('region', { name: 'Άννα Goblet Squats σετ 1', exact: true })
  await clickAdjustment(set, 'Αύξηση 1.25 kg Άννα Goblet Squats σετ 1')
  await clickAdjustment(set, 'Αύξηση 5 επαναλήψεων Άννα Goblet Squats σετ 1')
  await expect(set.getByLabel('Επαναλήψεις', { exact: true })).toHaveValue('15')
  await editor.getByRole('button', { name: 'Ακύρωση', exact: true }).click()
  await expect(page.getByText('6,25 kg / αλτήρα · 10 επ.', { exact: true })).toBeVisible()
  expect(requests).toHaveLength(0)
  await page.getByRole('button', { name: 'Επεξεργασία προπόνησης', exact: true }).click()
  editor = page.getByRole('dialog', { name: 'Επεξεργασία προπόνησης', exact: true })
  await editor.getByLabel('Ημερομηνία προπόνησης', { exact: true }).fill('2026-10-01')
  set = editor.getByRole('region', { name: 'Άννα Goblet Squats σετ 1', exact: true })
  await expect(set.getByLabel('Επαναλήψεις', { exact: true })).toHaveValue('10')
  await clickAdjustment(set, 'Αύξηση 2.5 kg Άννα Goblet Squats σετ 1')
  await clickAdjustment(set, 'Μείωση 2.5 kg Άννα Goblet Squats σετ 1')
  await clickAdjustment(set, 'Μείωση 1.25 kg Άννα Goblet Squats σετ 1')
  await expect(set.getByLabel('Βάρος (kg / αλτήρα)', { exact: true })).toHaveValue('5')
  await clickAdjustment(set, 'Αύξηση 2.5 kg Άννα Goblet Squats σετ 1')
  await clickAdjustment(set, 'Αύξηση 5 επαναλήψεων Άννα Goblet Squats σετ 1')
  await clickAdjustment(set, 'Μείωση 1 επαναλήψεων Άννα Goblet Squats σετ 1')
  await expect(set.getByLabel('Βάρος (kg / αλτήρα)', { exact: true })).toHaveValue('7.5')
  await expect(set.getByLabel('Επαναλήψεις', { exact: true })).toHaveValue('14')
  await editor.getByRole('button', { name: 'Δήμητρα', exact: true }).click()
  const other = editor.getByRole('region', { name: 'Δήμητρα TRX Rows σετ 1', exact: true })
  await clickAdjustment(other, 'Αύξηση 1 επαναλήψεων Δήμητρα TRX Rows σετ 1')
  await expect(other.getByLabel('Επαναλήψεις', { exact: true })).toHaveValue('11')
  await expect(editor.getByRole('region', { name: 'Δήμητρα Goblet Squats σετ 1', exact: true }).getByLabel('Κατάσταση σετ')).toHaveValue('skipped')
  expect(await editor.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  await page.screenshot({ path: `test-results/saved-editor-${info.project.name}.png`, fullPage: true })
  await context.setOffline(true)
  await editor.getByRole('button', { name: 'Αποθήκευση αλλαγών', exact: true }).click()
  await expect(editor).toHaveCount(0)
  await expect(page.getByText('7,5 kg / αλτήρα · 14 επ.', { exact: true })).toBeVisible()
  await expect(page.locator('.history-athlete.dimitra').getByText('11 επ.', { exact: true })).toBeVisible()
  expect(requests).toHaveLength(0)
  await context.setOffline(false); await synchronize(page)
  const saved = requests.find(r => r.endpoint === 'save_record' && r.kind === 'workout')!
  expect(saved.payload.date).toBe('2026-10-01')
  expect(remote.workouts[0].startedAt).toBe(workout.startedAt)
  expect(remote.workouts[0].completedAt).toBe(workout.completedAt)
  expect(remote.workouts[0].routine).toEqual(workout.routine)
  await page.goto(`/#/history?session=${workout.id}`); await page.reload()
  await expect(page.getByText('7,5 kg / αλτήρα · 14 επ.', { exact: true })).toBeVisible()
  await expect(page.getByRole('dialog').locator('.modal-heading p')).toContainText('1 Οκτωβρίου 2026')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Εξαγωγή CSV', exact: true }).click()
  expect((await downloadPromise).suggestedFilename()).toBe('workout-2026-10-01.csv')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('reps adjustments stay independent, respect limits and lock after recording', async ({ page }) => {
  await preview(page)
  const anna = page.getByTestId('panel-anna'), dimitra = page.getByTestId('panel-dimitra')
  const value = anna.getByLabel(/^Επαναλήψεις/), buttons = anna.locator('.value-increments')
  for (const button of await buttons.getByRole('button', { name: /^Μείωση/ }).all()) await expect(button).toBeDisabled()
  await clickAdjustment(anna, 'Αύξηση 5 επαναλήψεων Άννα Goblet Squats')
  await clickAdjustment(anna, 'Αύξηση 1 επαναλήψεων Άννα Goblet Squats', { clickCount: 2 })
  await expect(value).toHaveValue('7')
  await clickAdjustment(anna, 'Μείωση 5 επαναλήψεων Άννα Goblet Squats')
  await clickAdjustment(anna, 'Μείωση 1 επαναλήψεων Άννα Goblet Squats')
  await expect(value).toHaveValue('1')
  await expect(anna.getByRole('button', { name: 'Μείωση 1 επαναλήψεων Άννα Goblet Squats', exact: true })).toBeDisabled()
  await expect(dimitra.getByLabel(/^Επαναλήψεις/)).toHaveValue('')
  await value.fill('3595')
  await clickAdjustment(anna, 'Αύξηση 5 επαναλήψεων Άννα Goblet Squats')
  await expect(value).toHaveValue('3600')
  await buttons.getByRole('combobox').selectOption('1')
  await expect(anna.getByRole('button', { name: 'Αύξηση 1 επαναλήψεων Άννα Goblet Squats', exact: true })).toBeDisabled()
  await value.fill('10'); await anna.getByLabel(/^Βάρος/).fill('5')
  await anna.getByRole('button', { name: 'Καταγραφή', exact: true }).click()
  for (const button of await buttons.getByRole('button').all()) await expect(button).toBeDisabled()
  await expect(buttons.getByRole('combobox')).toBeDisabled()
  await page.reload(); await expect(value).toHaveValue('10')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('saved editing can restore unilateral and timed sets or remove a record without changing targets', async ({ page }) => {
  const { remote, workout } = await mockAccount(page, 'coach')
  await page.goto(`/#/history?session=${workout.id}`)
  await page.getByRole('button', { name: 'Επεξεργασία προπόνησης', exact: true }).click()
  const editor = page.getByRole('dialog', { name: 'Επεξεργασία προπόνησης', exact: true })
  await editor.getByLabel('Σταθμός επεξεργασίας').selectOption({ label: 'Σταθμός Γ' })
  const split = editor.getByRole('region', { name: 'Άννα Split Squats σετ 1', exact: true })
  await split.getByLabel('Κατάσταση σετ').selectOption('completed')
  await split.getByLabel('Βάρος (kg / αλτήρα)', { exact: true }).fill('6')
  await split.getByLabel('Επαναλήψεις', { exact: true }).fill('10')
  await clickAdjustment(split, 'Αύξηση 1 επαναλήψεων Άλλη πλευρά Άννα Split Squats σετ 1')
  await expect(split.getByLabel('Άλλη πλευρά', { exact: true })).toHaveValue('11')
  await expect(split.getByLabel('Επαναλήψεις', { exact: true })).toHaveValue('10')
  await editor.getByLabel('Σταθμός επεξεργασίας').selectOption({ label: 'Finisher' })
  const plank = editor.getByRole('region', { name: 'Άννα Plank σετ 1', exact: true })
  await plank.getByLabel('Κατάσταση σετ').selectOption('completed')
  await clickAdjustment(plank, 'Αύξηση 10 δευτερολέπτων Άννα Plank σετ 1')
  await clickAdjustment(plank, 'Αύξηση 5 δευτερολέπτων Άννα Plank σετ 1')
  await expect(plank.getByLabel('Δευτερόλεπτα', { exact: true })).toHaveValue('15')
  await expect(plank).toContainText('Στόχος: 45 δευτ.')
  await editor.getByLabel('Σταθμός επεξεργασίας').selectOption({ label: 'Σταθμός Α' })
  await editor.getByRole('region', { name: 'Άννα Goblet Squats σετ 1', exact: true }).getByLabel('Κατάσταση σετ').selectOption('pending')
  await editor.getByRole('button', { name: 'Αποθήκευση αλλαγών', exact: true }).click()
  await expect(page.getByText('6 kg / αλτήρα · 10 / 11 ανά πλευρά', { exact: true })).toBeVisible()
  await expect(page.getByText('15 δευτ.', { exact: true })).toBeVisible()
  await expect(page.locator('.result-history-row')).toHaveCount(43)
  await expect(page.getByText('6,25 kg / αλτήρα · 10 επ.', { exact: true })).toHaveCount(0)
  await page.getByRole('dialog').getByRole('button', { name: 'Κλείσιμο', exact: true }).click()
  await synchronize(page)
  expect(remote.workouts[0].routine).toEqual(workout.routine)
  expect(remote.workouts[0].status).toBe('partial')
  await page.goto(`/#/history?session=${workout.id}`); await page.reload()
  await expect(page.getByText('6 kg / αλτήρα · 10 / 11 ανά πλευρά', { exact: true })).toBeVisible()
})

test('seconds adjustments log actual time and leave the prescribed manual work timer untouched', async ({ page }) => {
  await preview(page, 3)
  const anna = page.getByTestId('panel-anna'), dimitra = page.getByTestId('panel-dimitra')
  const value = anna.getByLabel(/^Διάρκεια/)
  const plus10 = anna.getByRole('button', { name: /^Αύξηση 10 δευτερολέπτων/ })
  await anna.locator('.value-increments').getByRole('combobox').selectOption('10')
  await plus10.click()
  await anna.locator('.value-increments').getByRole('combobox').selectOption('5')
  await anna.getByRole('button', { name: /^Αύξηση 5 δευτερολέπτων/ }).click()
  await anna.getByRole('button', { name: /^Μείωση 5 δευτερολέπτων/ }).click()
  await expect(value).toHaveValue('10')
  await expect(dimitra.getByLabel(/^Διάρκεια/)).toHaveValue('')
  await anna.locator('.value-increments').getByRole('combobox').selectOption('10')
  await expect(anna.getByRole('button', { name: /^Μείωση 10 δευτερολέπτων/ })).toBeDisabled()
  const size = await plus10.boundingBox(); expect(size!.height).toBeGreaterThanOrEqual(44)
  await page.getByRole('button', { name: 'Άνοιγμα χρονομέτρου', exact: true }).click()
  await page.getByRole('button', { name: 'Άσκηση', exact: true }).click()
  await expect(page.locator('.timer-job')).toHaveCount(0)
  await expect(page.getByRole('dialog').getByRole('button', { name: '40″', exact: true })).toHaveCount(2)
  await page.getByRole('button', { name: 'Κλείσιμο', exact: true }).click()
  await anna.getByLabel(/^Βάρος/).fill('5')
  await anna.getByRole('button', { name: 'Καταγραφή', exact: true }).click()
  for (const button of await anna.locator('.value-increments').getByRole('button').all()) await expect(button).toBeDisabled()
  await expect(anna.locator('.value-increments').getByRole('combobox')).toBeDisabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('coach confirms offline discard and removes draft notes and timers without history', async ({ page, context }) => {
  const { requests, remote, workout } = await mockAccount(page, 'coach', true, { active: true })
  await page.goto(`/#/workout/${workout.id}`)
  await expect(page.getByTestId('panel-anna')).toBeVisible()
  await page.getByRole('button', { name: 'Άνοιγμα χρονομέτρου', exact: true }).click()
  await page.getByRole('button', { name: 'Έναρξη', exact: true }).click()
  await page.getByRole('button', { name: 'Κλείσιμο', exact: true }).click()
  await page.getByRole('button', { name: 'Επιλογές προπόνησης', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Διακοπή', exact: true }).click()
  let dialog = page.getByRole('dialog', { name: 'Διακοπή χωρίς αποθήκευση', exact: true })
  await dialog.getByRole('button', { name: 'Ακύρωση', exact: true }).click()
  await expect(page.getByTestId('panel-anna').getByLabel(/^Βάρος/)).toHaveValue('6.25')
  await expect(page.getByTestId('panel-anna').getByRole('textbox')).toHaveValue('private note')
  await context.setOffline(true)
  await page.getByRole('button', { name: 'Επιλογές προπόνησης', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Διακοπή', exact: true }).click()
  dialog = page.getByRole('dialog', { name: 'Διακοπή χωρίς αποθήκευση', exact: true })
  await dialog.getByRole('button', { name: 'Διακοπή χωρίς αποθήκευση', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Ξεκινήστε προπόνηση', exact: true })).toBeVisible()
  await expect(page.locator('.resume-strip')).toHaveCount(0)
  await expect(page.locator('.timer-fab')).toContainText('Χρονόμετρο')
  expect(requests).toHaveLength(0)
  await context.setOffline(false); await synchronize(page)
  expect(requests.find(r => r.endpoint === 'delete_record' && r.kind === 'workout')?.payload.discard).toBe(true)
  expect(remote.workouts).toEqual([]); expect(remote.notes).toEqual([])
  await page.goto('/#/history'); await page.reload()
  await expect(page.getByText('Το ιστορικό σας ξεκινά εδώ.', { exact: true })).toBeVisible()
})

test('starting another routine offers resume or confirmed replacement and syncs one empty active workout', async ({ page, context }) => {
  const { requests, remote, workout } = await mockAccount(page, 'coach', true, { active: true })
  // The production PWA precaches routes; the development server does not.
  await page.goto(`/#/workout/${workout.id}`)
  await expect(page.getByTestId('panel-anna')).toBeVisible()
  await page.goto('/#/')
  await page.getByRole('button', { name: 'Έναρξη Προπόνηση 2', exact: true }).click()
  const choice = page.getByRole('dialog', { name: 'Έτοιμες για προπόνηση;', exact: true })
  await expect(choice.getByLabel('Επιλογή προπόνησης').locator('option:checked')).toContainText('Προπόνηση 2')
  await expect(choice.getByRole('button', { name: 'Συνέχεια τρέχουσας', exact: true })).toBeVisible()
  await choice.getByRole('button', { name: 'Διακοπή και νέα προπόνηση', exact: true }).click()
  let confirmation = page.getByRole('dialog', { name: 'Διακοπή και νέα προπόνηση', exact: true })
  await confirmation.getByRole('button', { name: 'Ακύρωση', exact: true }).click()
  expect(remote.workouts[0].id).toBe(workout.id); expect(requests).toHaveLength(0)
  await context.setOffline(true)
  await choice.getByRole('button', { name: 'Διακοπή και νέα προπόνηση', exact: true }).click()
  confirmation = page.getByRole('dialog', { name: 'Διακοπή και νέα προπόνηση', exact: true })
  await confirmation.getByRole('button', { name: 'Διακοπή και έναρξη', exact: true }).click()
  await expect(page.getByTestId('panel-anna')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Προπόνηση 2.', exact: true })).toBeVisible()
  await expect(page.getByTestId('panel-anna').getByLabel(/^Επαναλήψεις/)).toHaveValue('')
  await expect(page.getByTestId('panel-anna').getByRole('textbox')).toHaveValue('')
  expect(requests).toHaveLength(0)
  await context.setOffline(false); await synchronize(page)
  expect(requests.filter(r => r.endpoint === 'delete_record')).toHaveLength(1)
  expect(requests.filter(r => r.endpoint === 'save_record' && r.kind === 'workout')).toHaveLength(1)
  expect(remote.workouts).toHaveLength(1)
  expect(remote.workouts[0].id).not.toBe(workout.id)
  expect(remote.workouts[0].status).toBe('active')
  expect(remote.workouts[0].results).toEqual({}); expect(remote.notes).toEqual([])
  await page.goto('/#/'); await page.reload()
  await page.getByRole('button', { name: 'Συνέχεια προπόνησης', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Προπόνηση 2.', exact: true })).toBeVisible()
  await page.goto('/#/history')
  await expect(page.getByText('Το ιστορικό σας ξεκινά εδώ.', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
