import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, Dumbbell, Activity, Flame, CalendarCheck2, CheckCheck, Users, TrendingUp, Play, Target, Plus } from 'lucide-react'
import { useWorkspace } from '../context/Workspace'
import { useAuth } from '../context/Auth'
import { athletes, athleteIds, createWorkout, discardActiveWorkout, workoutDate, compareWorkoutDates, formatDate, progress, weightStats, type AthleteId, type Routine } from '../lib/model'
import { number, signed } from '../lib/utils'
import { useTimer } from '../context/Timer'
import { Button, Card, Badge, Modal, DeleteConfirmation, SectionHeading, EmptyState, ProgressBar } from '../components/ui'

export function Dashboard() {
  const { data, edit, loading } = useWorkspace(), { identity, local } = useAuth(), timer = useTimer(), navigate = useNavigate()
  const [selected, setSelected] = useState<Routine | null>(null), [participants, setParticipants] = useState<AthleteId[]>([...athleteIds]), [busy, setBusy] = useState(false), [replacing, setReplacing] = useState(false)
  const active = data.workouts.find(w => w.status === 'active'), completed = data.workouts.filter(w => w.status !== 'active')
  const canDiscard = identity?.role === 'coach' && (local || data.workoutDiscard === true)
  const completedSets = completed.flatMap(w => Object.values(w.results)).filter(r => r.status === 'completed').length
  const start = async (replace = false) => {
    if (!selected || !participants.length) return
    setBusy(true)
    const workout = createWorkout(selected, data.program.id, participants)
    try {
      await edit(w => {
        const changes = replace && active ? discardActiveWorkout(w, active.id) : []
        if (w.workouts.some(x => x.status === 'active')) throw new Error('Υπάρχει ήδη μια ενεργή προπόνηση. Συνεχίστε ή διακόψτε την πριν ξεκινήσετε άλλη.')
        w.workouts.push(workout)
        return [...changes, ...(w.program.revision === 0 ? [{ kind: 'program' as const, payload: w.program }] : []), { kind: 'workout', payload: workout }]
      })
      if (replace) timer.clear()
      navigate(`/workout/${workout.id}`)
    } catch (error) { if (replace) throw error } finally { setBusy(false) }
  }
  const choose = (routine: Routine) => { if (identity?.role !== 'coach') navigate(`/program?day=${routine.id}`); else setSelected(routine) }
  return <><div className="page-heading"><div><span className="eyebrow">ΤΟ TRAINING DASHBOARD ΜΑΣ</span><h1>Καλώς ήρθατε στο Lab<span className="title-dot">.</span></h1><p>Η προπόνηση και η πρόοδος, σε ένα μέρος.</p></div><span className="date-label">{formatDate(new Date().toISOString(), true)}</span></div>
    <section className="dashboard-hero"><div className="hero-content"><Badge className="hero-badge"><span className="live-dot" />{active ? 'ΠΡΟΠΟΝΗΣΗ ΣΕ ΕΞΕΛΙΞΗ' : 'ΕΤΟΙΜΕΣ ΓΙΑ ΤΟ ΕΠΟΜΕΝΟ ΒΗΜΑ'}</Badge><h2>{active ? <>Πάμε να ολοκληρώσουμε<br />αυτό που ξεκινήσαμε.</> : <>Η συνέπεια χτίζεται.<br /><span>Ένα σετ τη φορά.</span></>}</h2><p>{active ? `${active.routine.name} · ${active.routine.stations[active.stationIndex].name} · Γύρος ${active.roundIndex + 1}` : 'Ένα πρόγραμμα. Δύο ξεχωριστές διαδρομές προόδου.'}</p><Button disabled={loading} onClick={() => active ? navigate(`/workout/${active.id}`) : choose(data.program.routines[0])}><Play size={17} fill="currentColor" />{active ? 'Συνέχεια προπόνησης' : identity?.role === 'coach' ? 'Ξεκινήστε προπόνηση' : 'Δείτε το πρόγραμμά σας'}<ArrowRight size={17} /></Button></div><div className="hero-athletes"><div className="hero-orbit"><span className="orbit-ring orbit-one" /><span className="orbit-ring orbit-two" /><span className="orbit-ring orbit-three" /><div className="hero-athlete anna"><span>Α</span><div><strong>Άννα</strong><small>Η δική της πρόοδος</small></div></div><div className="hero-athlete dimitra"><span>Δ</span><div><strong>Δήμητρα</strong><small>Η δική της πρόοδος</small></div></div><div className="hero-orbit-center"><Dumbbell size={27} /></div></div><span className="hero-caption">TRAIN TOGETHER. GROW INDIVIDUALLY.</span></div></section>
    <div className="stats-grid">{[{ label: 'Καταγεγραμμένες προπονήσεις', value: completed.length, icon: CalendarCheck2, caption: 'Η συνέπειά μας στην πράξη' }, { label: 'Ολοκληρωμένα σετ', value: completedSets, icon: CheckCheck, caption: 'Κάθε προσπάθεια καταγράφεται' }, { label: 'Αθλήτριες στην ομάδα', value: 2, icon: Users, caption: 'Άννα & Δήμητρα' }].map(({ label, value, icon: Icon, caption }) => <Card className="stat-card" key={label}><div><span>{label}</span><Icon size={20} /></div><strong>{value.toString().padStart(2, '0')}</strong><small>{caption}</small></Card>)}</div>
    <SectionHeading title="Το πρόγραμμά μας" subtitle="Τρεις προπονήσεις, με διαφορετική έμφαση." action={<button className="text-link" onClick={() => navigate('/program')}>Όλο το πρόγραμμα<ArrowUpRight size={16} /></button>} /><div className="routine-grid">{data.program.routines.map((routine, i) => {
      const Icon = [Dumbbell, Activity, Flame][i % 3]
      return <Card className={`routine-card routine-${i}`} key={routine.id}><div className="routine-card-top"><span className="routine-icon"><Icon size={24} /></span><span className="routine-number">0{i + 1}</span></div><span className="eyebrow">{routine.name}</span><h3>{routine.subtitle}</h3><p>{routine.focus}</p><div className="routine-tags"><Badge>{routine.stations.filter(s => s.name !== 'Finisher').length} σταθμοί</Badge>{routine.stations.some(s => s.name === 'Finisher') && <Badge>+ Finisher</Badge>}<Badge>{routine.stations[0]?.rest ?? '—'}″ διάλειμμα</Badge></div><div className="routine-card-bottom"><span>{routine.stations.map(s => s.rounds).reduce((a, b) => a + b, 0)} γύροι συνολικά</span><button onClick={() => choose(routine)} aria-label={`Έναρξη ${routine.name}`}><ArrowRight size={20} /></button></div></Card>
    })}</div>
    <div className="dashboard-bottom"><Card className="weight-overview"><SectionHeading title="Πρόοδος βάρους" subtitle="Κάθε αθλήτρια, με τη δική της αφετηρία." action={<button className="icon-link" aria-label="Όλη η πρόοδος" onClick={() => navigate('/progress')}><ArrowUpRight size={19} /></button>} /><div className="weight-summary-pair">{athleteIds.map(a => { const stats = weightStats(data.weighIns, a), goal = data.goals[a].value; return <div key={a} className={`weight-mini ${a}`}><span className={`avatar ${a}`}>{athletes[a].initial}</span><div><strong>{athletes[a].name}</strong><span>{stats.latest ? <>{number(stats.latest.weight)} <small>kg</small></> : '—'}</span><small>{stats.change !== null ? `${signed(stats.change)} kg από την αρχή` : 'Χωρίς μέτρηση ακόμη'}</small></div></div> })}</div><div className="weight-overview-footer"><TrendingUp size={17} /><span>{data.weighIns.length ? 'Δείτε την εξέλιξη και τους προσωπικούς στόχους.' : 'Η πρώτη μέτρηση είναι η αφετηρία.'}</span><Button variant="secondary" size="small" onClick={() => navigate('/progress')}><Plus size={15} />Μέτρηση</Button></div></Card><Card className="recent-overview"><SectionHeading title="Πρόσφατη δραστηριότητα" action={<button className="icon-link" aria-label="Όλο το ιστορικό" onClick={() => navigate('/history')}><ArrowUpRight size={19} /></button>} />{completed.length ? [...completed].sort(compareWorkoutDates).slice(0, 3).map(w => <button className="recent-row" key={w.id} onClick={() => navigate(`/history?session=${w.id}`)}><span className="recent-icon"><Dumbbell size={19} /></span><span><strong>{w.routine.name}</strong><small>{formatDate(workoutDate(w))} · {w.status === 'partial' ? 'Μερική καταγραφή' : 'Ολοκληρώθηκε'}</small></span><ArrowRight size={17} /></button>) : <EmptyState icon={<CalendarCheck2 size={25} />} title="Η αρχή είναι μπροστά μας." description="Οι ολοκληρωμένες προπονήσεις σας θα εμφανίζονται εδώ." />}</Card></div>
    {active && <Card className="active-summary"><div><Dumbbell size={20} /><strong>Η προπόνησή σας έχει αποθηκευτεί.</strong><span>{progress(active).recorded}/{progress(active).total} καταγραφές</span></div><ProgressBar value={progress(active).percent} /></Card>}
    <Modal open={Boolean(selected)} onOpenChange={open => !open && setSelected(null)} title="Έτοιμες για προπόνηση;" description={selected ? `${selected.name} · ${selected.focus}` : ''}>
      <label className="workout-routine-choice">Επιλογή προπόνησης<select value={selected?.id || ''} disabled={busy} onChange={event => setSelected(data.program.routines.find(routine => routine.id === event.target.value) || null)}>{data.program.routines.map(routine => <option key={routine.id} value={routine.id}>{routine.name} · {routine.subtitle}</option>)}</select></label>
      {active && <div className="inline-notice workout-replacement-notice">Υπάρχει ενεργή προπόνηση: <strong>{active.routine.name}</strong>. Μπορείτε να τη συνεχίσετε ή να τη διακόψετε χωρίς αποθήκευση για να ξεκινήσετε τη νέα.{!canDiscard && <p>Η διακοπή χρειάζεται ενεργοποίηση για την ομάδα.</p>}</div>}<div className="participant-choice">{athleteIds.map(a => <label key={a} className={participants.includes(a) ? 'selected' : ''}><span className={`avatar ${a}`}>{athletes[a].initial}</span><strong>{athletes[a].name}</strong><input type="checkbox" checked={participants.includes(a)} onChange={e => setParticipants(previous => e.target.checked ? [...previous, a] : previous.filter(p => p !== a))} /></label>)}</div><p className="muted small">Επιλέξτε ποιες συμμετέχουν. Άσκηση → αλλαγή → χειροκίνητο διάλειμμα.</p><div className="modal-actions"><Button variant="secondary" onClick={() => setSelected(null)}>Ακύρωση</Button>{active ? <><Button variant="secondary" onClick={() => navigate(`/workout/${active.id}`)}>Συνέχεια τρέχουσας</Button><Button variant="danger" disabled={!participants.length || busy || !canDiscard} onClick={() => setReplacing(true)}>Διακοπή και νέα προπόνηση</Button></> : <Button disabled={!participants.length || busy} onClick={() => void start()}><Play size={17} />{busy ? 'Αποθήκευση…' : 'Έναρξη προπόνησης'}</Button>}</div></Modal>
    <DeleteConfirmation open={replacing} onOpenChange={setReplacing} title="Διακοπή και νέα προπόνηση" description={active && selected ? `${active.routine.name} → ${selected.name}` : ''} confirmLabel="Διακοπή και έναρξη" message="Τα σετ και οι σημειώσεις της τρέχουσας προπόνησης θα διαγραφούν χωρίς καταγραφή στο ιστορικό. Η νέα προπόνηση θα ξεκινήσει με κενά αποτελέσματα." onConfirm={async () => { if (!canDiscard || !active) throw new Error('Η τρέχουσα προπόνηση δεν είναι διαθέσιμη για διακοπή.'); await start(true) }} />
  </>
}
