import { useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { ArrowUpRight, Dumbbell, History as HistoryIcon, Pencil, LockKeyhole, Search, Download, Trash2 } from 'lucide-react'
import { useWorkspace } from '../context/Workspace'
import { useAuth } from '../context/Auth'
import { athletes, athleteIds, formatDate, workoutDate, compareWorkoutDates, applyWorkoutEdits, deleteLoggedSet, type AthleteId, type SetResult, type Workout } from '../lib/model'
import { number } from '../lib/utils'
import { Button, Card, Badge, Modal, DeleteConfirmation, EmptyState } from '../components/ui'
import { WorkoutEditor } from '../components/WorkoutEditor'

export function History() {
  const { data, edit } = useWorkspace(), { identity, local } = useAuth(), navigate = useNavigate(), [params, setParams] = useSearchParams()
  const [query, setQuery] = useState(''), [editing, setEditing] = useState<{ workout: Workout; athlete?: AthleteId; station?: string } | null>(null)
  const [deleting, setDeleting] = useState<{ workout: Workout; result?: SetResult } | null>(null)
  const canDelete = identity?.role === 'coach' && (local || data.historyDeletion === true)
  const sessions = [...data.workouts].filter(w => w.status !== 'active' && `${w.routine.name} ${w.routine.focus}`.toLowerCase().includes(query.toLowerCase())).sort(compareWorkoutDates)
  const selected = data.workouts.find(w => w.id === params.get('session'))
  const comparisons = identity?.role === 'coach' ? sessions.map(w => ({ id: w.id, date: workoutDate(w), name: w.routine.name, results: { anna: { completed: Object.values(w.results).filter(r => r.athlete === 'anna' && r.status === 'completed').length }, dimitra: { completed: Object.values(w.results).filter(r => r.athlete === 'dimitra' && r.status === 'completed').length } } })) : data.comparisons
  return <><div className="page-heading"><div><span className="eyebrow">ΚΑΘΕ ΠΡΟΣΠΑΘΕΙΑ ΜΕΤΡΑΕΙ</span><h1>Ιστορικό προπονήσεων<span className="title-dot">.</span></h1><p>Όσα κάναμε, όπως ακριβώς τα καταγράψαμε.</p></div><Badge>{sessions.length} καταγραφές</Badge></div><Card className="history-card"><div className="history-toolbar"><h2>Οι προπονήσεις μας</h2><label className="search-input"><Search size={17} /><input placeholder="Αναζήτηση προπόνησης" aria-label="Αναζήτηση προπόνησης" value={query} onChange={e => setQuery(e.target.value)} /></label></div>{sessions.length ? <div className="table-scroll"><table className="history-table"><thead><tr><th>Προπόνηση</th><th>Ημερομηνία</th><th>Αθλήτριες</th><th>Καταγραφή</th><th>Κατάσταση</th><th /></tr></thead><tbody>{sessions.map(w => <tr key={w.id} onClick={() => setParams({ session: w.id })}><td><div className="table-workout"><span className="recent-icon"><Dumbbell size={19} /></span><div><strong>{w.routine.name}</strong><small>{w.routine.subtitle}</small></div></div></td><td>{formatDate(workoutDate(w), true)}</td><td><div className="small-avatar-pair">{w.participants.map(a => <span className={`avatar ${a}`} key={a} title={athletes[a].name}>{athletes[a].initial}</span>)}</div></td><td>{Object.values(w.results).filter(r => r.status === 'completed').length} αποτελέσματα</td><td><Badge className={w.status === 'completed' ? 'complete-badge' : 'partial-badge'}>{w.status === 'completed' ? 'Ολοκληρώθηκε' : 'Μερική'}</Badge></td><td><button className="icon-link" aria-label={`Προβολή ${w.routine.name} ${formatDate(workoutDate(w))}`} onClick={e => { e.stopPropagation(); setParams({ session: w.id }) }}><ArrowUpRight size={19} /></button>{identity?.role === 'coach' && <button className="icon-link" aria-label={`Επεξεργασία προπόνησης ${w.routine.name} ${formatDate(workoutDate(w))}`} onClick={e => { e.stopPropagation(); setEditing({ workout: structuredClone(w) }) }}><Pencil size={16} /></button>}{identity?.role === 'coach' && <button className="icon-link delete-link" disabled={!canDelete} aria-label={`Διαγραφή προπόνησης ${w.routine.name} ${formatDate(workoutDate(w))}`} onClick={e => { e.stopPropagation(); setDeleting({ workout: w }) }}><Trash2 size={16} /></button>}</td></tr>)}</tbody></table></div> : <EmptyState icon={<HistoryIcon size={30} />} title={query ? 'Δεν βρέθηκε προπόνηση.' : 'Το ιστορικό σας ξεκινά εδώ.'} description={query ? 'Δοκιμάστε διαφορετική αναζήτηση.' : 'Ολοκληρώστε την πρώτη προπόνηση για να δείτε όλα τα σετ, τα βάρη και τις επαναλήψεις σας.'} action={!query && <Button onClick={() => navigate('/')}><Dumbbell size={17} />Επιλογή προπόνησης</Button>} />}</Card>
    {comparisons.length > 0 && <Card className="comparison-card"><div className="section-heading"><div><h2>Συγκρίσεις ομάδας</h2><p>Ολοκληρωμένα αποτελέσματα ανά προπόνηση, για κάθε αθλήτρια.</p></div></div><div className="table-scroll"><table><thead><tr><th>Προπόνηση</th><th>Ημερομηνία</th><th>Άννα</th><th>Δήμητρα</th></tr></thead><tbody>{comparisons.map(c => <tr key={c.id}><td>{c.name}</td><td>{formatDate(c.date)}</td><td><span className="athlete-label anna"><i />{c.results.anna.completed}</span></td><td><span className="athlete-label dimitra"><i />{c.results.dimitra.completed}</span></td></tr>)}</tbody></table></div></Card>}
    <Modal wide open={Boolean(selected)} onOpenChange={open => !open && setParams({})} title={selected?.routine.name || 'Καταγραφή'} description={selected ? `${formatDate(workoutDate(selected), true)} · ${selected.routine.focus}` : ''}>{selected && <><div className="session-detail-meta"><Badge className={selected.status === 'completed' ? 'complete-badge' : 'partial-badge'}>{selected.status === 'completed' ? 'Ολοκληρώθηκε' : 'Μερική καταγραφή'}</Badge><Button variant="secondary" size="small" onClick={() => downloadSession(selected)}><Download size={15} />Εξαγωγή CSV</Button>{identity?.role === 'coach' && selected.status !== 'active' && <Button variant="secondary" size="small" onClick={() => setEditing({ workout: structuredClone(selected) })}><Pencil size={15} />Επεξεργασία προπόνησης</Button>}{identity?.role === 'coach' && selected.status !== 'active' && <Button variant="danger" size="small" disabled={!canDelete} onClick={() => setDeleting({ workout: selected })}><Trash2 size={15} />Διαγραφή προπόνησης</Button>}</div><div className="history-detail-pair">{athleteIds.filter(a => selected.participants.includes(a)).map(a => <div className={`history-athlete ${a}`} key={a}><div className="history-athlete-heading"><span className={`avatar ${a}`}>{athletes[a].initial}</span><h3>{athletes[a].name}</h3></div>{selected.routine.stations.map(station => <div className="history-station" key={station.id}><h4>{station.name}</h4>{Object.values(selected.results).filter(r => r.athlete === a && r.station === station.id && r.status !== 'pending').sort((x, y) => x.round - y.round || x.slot - y.slot).map(r => <div className="result-history-row" key={r.key}><span className="set-number">{r.round + 1}</span><div><strong>{r.movement.name}</strong><small>{r.status === 'skipped' ? 'Παραλείφθηκε' : `${r.weight !== null ? `${number(r.weight, 2)} kg / αλτήρα · ` : ''}${r.value}${r.otherSide != null ? ` / ${r.otherSide}` : ''} ${r.movement.metric === 'seconds' ? 'δευτ.' : r.movement.unilateral ? 'ανά πλευρά' : 'επ.'}`}</small></div>{identity?.role === 'coach' && <button className="icon-link" aria-label={`Διόρθωση ${athletes[a].name} ${r.movement.name} σετ ${r.round + 1}`} onClick={() => setEditing({ workout: structuredClone(selected), athlete: a, station: r.station })}><Pencil size={14} /></button>}{identity?.role === 'coach' && selected.status !== 'active' && <button className="icon-link delete-link" disabled={!canDelete} aria-label={`Διαγραφή σετ ${athletes[a].name} ${r.movement.name} σετ ${r.round + 1}`} onClick={() => setDeleting({ workout: selected, result: r })}><Trash2 size={15} /></button>}</div>)}</div>)}{identity?.role === 'coach' && data.notes.find(n => n.workoutId === selected.id && n.athlete === a)?.text && <div className="private-note-display"><span><LockKeyhole size={13} />Ιδιωτική σημείωση</span><p>{data.notes.find(n => n.workoutId === selected.id && n.athlete === a)?.text}</p></div>}</div>)}</div></>}</Modal>
    {identity?.role === 'coach' && !canDelete && <p className="muted small deletion-availability">Η διαγραφή ιστορικού θα είναι διαθέσιμη μόλις ενεργοποιηθεί για την ομάδα.</p>}
    <DeleteConfirmation open={Boolean(deleting)} onOpenChange={open => !open && setDeleting(null)} title={deleting?.result ? 'Διαγραφή καταγεγραμμένου σετ' : 'Διαγραφή προπόνησης'} description={deleting ? deleting.result ? `${athletes[deleting.result.athlete].name} · ${deleting.result.movement.name} · Σετ ${deleting.result.round + 1}` : `${deleting.workout.routine.name} · ${formatDate(workoutDate(deleting.workout), true)} · Όλα τα αποτελέσματα και οι σημειώσεις αυτής της προπόνησης` : ''} onConfirm={async () => {
      if (!deleting || !canDelete) throw new Error('Δεν επιτρέπεται η διαγραφή.')
      await edit(w => {
        const index = w.workouts.findIndex(x => x.id === deleting.workout.id)
        if (index < 0) return []
        const workout = w.workouts[index]
        if (workout.status === 'active') throw new Error('Η προπόνηση είναι ακόμη σε εξέλιξη.')
        if (deleting.result) { const updated = deleteLoggedSet(workout, deleting.result.key); w.workouts[index] = updated; return [{ kind: 'workout', payload: updated }] }
        w.workouts = w.workouts.filter(x => x.id !== workout.id)
        w.notes = w.notes.filter(n => n.workoutId !== workout.id)
        w.comparisons = w.comparisons.filter(c => c.id !== workout.id)
        return [{ kind: 'workout', payload: { id: workout.id, revision: workout.revision, deleted: true } }]
      })
      if (!deleting.result && selected?.id === deleting.workout.id) setParams({})
    }} />
    {editing && <WorkoutEditor workout={editing.workout} athlete={editing.athlete} station={editing.station} onClose={() => setEditing(null)} onSave={async draft => {
      if (identity?.role !== 'coach') throw new Error('Η επεξεργασία επιτρέπεται μόνο στον προπονητή.')
      await edit(w => { const index = w.workouts.findIndex(x => x.id === draft.id); if (index < 0) throw new Error('Η προπόνηση έχει διαγραφεί.'); const updated = applyWorkoutEdits(w.workouts[index], editing.workout, draft); w.workouts[index] = updated; return [{ kind: 'workout', payload: updated }] })
    }} />}

  </>
}
function downloadSession(workout: Workout) {
  const quote = (value: unknown) => { let text = String(value ?? ''); if (/^[=+@\-\t\r]/.test(text)) text = `'${text}`; return `"${text.replaceAll('"', '""')}"` }
  const rows = [['Αθλήτρια', 'Άσκηση', 'Σετ', 'Βάρος kg ανά αλτήρα', 'Επαναλήψεις', 'Δευτερόλεπτα', 'Άλλη πλευρά', 'Κατάσταση'], ...Object.values(workout.results).filter(r => r.status !== 'pending').map(r => [athletes[r.athlete].name, r.movement.name, r.round + 1, r.weight, r.movement.metric === 'reps' ? r.value : '', r.movement.metric === 'seconds' ? r.value : '', r.otherSide, r.status])]
  const url = URL.createObjectURL(new Blob(['\ufeff' + rows.map(row => row.map(quote).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' }))
  const link = document.createElement('a'); link.href = url; link.download = `workout-${workoutDate(workout)}.csv`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 500)
}
