import { useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { ArrowUpRight, Check, Dumbbell, History as HistoryIcon, Pencil, LockKeyhole, Search, Download } from 'lucide-react'
import { useWorkspace } from '../context/Workspace'
import { useAuth } from '../context/Auth'
import { athletes, athleteIds, allExpected, formatDate, validResult, type SetResult, type Workout } from '../lib/model'
import { number } from '../lib/utils'
import { Button, Card, Badge, Modal, EmptyState } from '../components/ui'

export function History() {
  const { data, edit } = useWorkspace(), { identity } = useAuth(), navigate = useNavigate(), [params, setParams] = useSearchParams()
  const [query, setQuery] = useState(''), [correction, setCorrection] = useState<{ session: string; result: SetResult } | null>(null), [saving, setSaving] = useState(false)
  const sessions = [...data.workouts].filter(w => w.status !== 'active' && `${w.routine.name} ${w.routine.focus}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => b.startedAt.localeCompare(a.startedAt))
  const selected = data.workouts.find(w => w.id === params.get('session'))
  const comparisons = identity?.role === 'coach' ? sessions.map(w => ({ id: w.id, date: w.completedAt || w.startedAt, name: w.routine.name, results: { anna: { completed: Object.values(w.results).filter(r => r.athlete === 'anna' && r.status === 'completed').length }, dimitra: { completed: Object.values(w.results).filter(r => r.athlete === 'dimitra' && r.status === 'completed').length } } })) : data.comparisons
  return <><div className="page-heading"><div><span className="eyebrow">ΚΑΘΕ ΠΡΟΣΠΑΘΕΙΑ ΜΕΤΡΑΕΙ</span><h1>Ιστορικό προπονήσεων<span className="title-dot">.</span></h1><p>Όσα κάναμε, όπως ακριβώς τα καταγράψαμε.</p></div><Badge>{sessions.length} καταγραφές</Badge></div><Card className="history-card"><div className="history-toolbar"><h2>Οι προπονήσεις μας</h2><label className="search-input"><Search size={17} /><input placeholder="Αναζήτηση προπόνησης" aria-label="Αναζήτηση προπόνησης" value={query} onChange={e => setQuery(e.target.value)} /></label></div>{sessions.length ? <div className="table-scroll"><table className="history-table"><thead><tr><th>Προπόνηση</th><th>Ημερομηνία</th><th>Αθλήτριες</th><th>Καταγραφή</th><th>Κατάσταση</th><th /></tr></thead><tbody>{sessions.map(w => <tr key={w.id} onClick={() => setParams({ session: w.id })}><td><div className="table-workout"><span className="recent-icon"><Dumbbell size={19} /></span><div><strong>{w.routine.name}</strong><small>{w.routine.subtitle}</small></div></div></td><td>{formatDate(w.completedAt || w.startedAt, true)}</td><td><div className="small-avatar-pair">{w.participants.map(a => <span className={`avatar ${a}`} key={a} title={athletes[a].name}>{athletes[a].initial}</span>)}</div></td><td>{Object.values(w.results).filter(r => r.status === 'completed').length} αποτελέσματα</td><td><Badge className={w.status === 'completed' ? 'complete-badge' : 'partial-badge'}>{w.status === 'completed' ? 'Ολοκληρώθηκε' : 'Μερική'}</Badge></td><td><button className="icon-link" aria-label={`Προβολή ${w.routine.name} ${formatDate(w.startedAt)}`} onClick={e => { e.stopPropagation(); setParams({ session: w.id }) }}><ArrowUpRight size={19} /></button></td></tr>)}</tbody></table></div> : <EmptyState icon={<HistoryIcon size={30} />} title={query ? 'Δεν βρέθηκε προπόνηση.' : 'Το ιστορικό σας ξεκινά εδώ.'} description={query ? 'Δοκιμάστε διαφορετική αναζήτηση.' : 'Ολοκληρώστε την πρώτη προπόνηση για να δείτε όλα τα σετ, τα βάρη και τις επαναλήψεις σας.'} action={!query && <Button onClick={() => navigate('/')}><Dumbbell size={17} />Επιλογή προπόνησης</Button>} />}</Card>
    {comparisons.length > 0 && <Card className="comparison-card"><div className="section-heading"><div><h2>Συγκρίσεις ομάδας</h2><p>Ολοκληρωμένα αποτελέσματα ανά προπόνηση, για κάθε αθλήτρια.</p></div></div><div className="table-scroll"><table><thead><tr><th>Προπόνηση</th><th>Ημερομηνία</th><th>Άννα</th><th>Δήμητρα</th></tr></thead><tbody>{comparisons.map(c => <tr key={c.id}><td>{c.name}</td><td>{formatDate(c.date)}</td><td><span className="athlete-label anna"><i />{c.results.anna.completed}</span></td><td><span className="athlete-label dimitra"><i />{c.results.dimitra.completed}</span></td></tr>)}</tbody></table></div></Card>}
    <Modal wide open={Boolean(selected)} onOpenChange={open => !open && setParams({})} title={selected?.routine.name || 'Καταγραφή'} description={selected ? `${formatDate(selected.completedAt || selected.startedAt, true)} · ${selected.routine.focus}` : ''}>{selected && <><div className="session-detail-meta"><Badge className={selected.status === 'completed' ? 'complete-badge' : 'partial-badge'}>{selected.status === 'completed' ? 'Ολοκληρώθηκε' : 'Μερική καταγραφή'}</Badge><Button variant="secondary" size="small" onClick={() => downloadSession(selected)}><Download size={15} />Εξαγωγή CSV</Button></div><div className="history-detail-pair">{athleteIds.filter(a => selected.participants.includes(a)).map(a => <div className={`history-athlete ${a}`} key={a}><div className="history-athlete-heading"><span className={`avatar ${a}`}>{athletes[a].initial}</span><h3>{athletes[a].name}</h3></div>{selected.routine.stations.map(station => <div className="history-station" key={station.id}><h4>{station.name}</h4>{Object.values(selected.results).filter(r => r.athlete === a && r.station === station.id && r.status !== 'pending').sort((x, y) => x.round - y.round || x.slot - y.slot).map(r => <div className="result-history-row" key={r.key}><span className="set-number">{r.round + 1}</span><div><strong>{r.movement.name}</strong><small>{r.status === 'skipped' ? 'Παραλείφθηκε' : `${r.weight !== null ? `${number(r.weight)} kg / αλτήρα · ` : ''}${r.value}${r.otherSide != null ? ` / ${r.otherSide}` : ''} ${r.movement.metric === 'seconds' ? 'δευτ.' : r.movement.unilateral ? 'ανά πλευρά' : 'επ.'}`}</small></div>{identity?.role === 'coach' && <button className="icon-link" aria-label={`Διόρθωση ${athletes[a].name} ${r.movement.name} σετ ${r.round + 1}`} onClick={() => setCorrection({ session: selected.id, result: structuredClone(r) })}><Pencil size={14} /></button>}</div>)}</div>)}{identity?.role === 'coach' && data.notes.find(n => n.workoutId === selected.id && n.athlete === a)?.text && <div className="private-note-display"><span><LockKeyhole size={13} />Ιδιωτική σημείωση</span><p>{data.notes.find(n => n.workoutId === selected.id && n.athlete === a)?.text}</p></div>}</div>)}</div></>}</Modal>
    <Modal open={Boolean(correction)} onOpenChange={open => !open && setCorrection(null)} title="Διόρθωση καταγραφής" description={correction ? `${athletes[correction.result.athlete].name} · ${correction.result.movement.name} · Σετ ${correction.result.round + 1}` : ''}>{correction && <form onSubmit={async e => { e.preventDefault(); setSaving(true); try { await edit(w => { const workout = w.workouts.find(s => s.id === correction.session)!; workout.results[correction.result.key] = correction.result.status === 'skipped' ? { ...correction.result, weight: null, value: null, otherSide: null } : correction.result; workout.status = allExpected(workout).every(r => workout.results[r.key]?.status === 'completed') ? 'completed' : 'partial'; return [{ kind: 'workout', payload: workout }] }); setCorrection(null) } catch { /* surfaced by context */ } finally { setSaving(false) } }}><label>Κατάσταση<select value={correction.result.status} onChange={e => setCorrection({ ...correction, result: { ...correction.result, status: e.target.value as SetResult['status'] } })}><option value="completed">Ολοκληρώθηκε</option><option value="skipped">Παραλείφθηκε</option></select></label>{correction.result.status !== 'skipped' && <div className="form-grid">{correction.result.movement.loaded && <label>Βάρος (kg / αλτήρα)<input type="number" min="0" step="any" value={correction.result.weight ?? ''} onChange={e => setCorrection({ ...correction, result: { ...correction.result, weight: e.target.value === '' ? null : Number(e.target.value) } })} /></label>}<label>{correction.result.movement.metric === 'seconds' ? 'Δευτερόλεπτα' : 'Επαναλήψεις'}<input type="number" min="1" step="1" value={correction.result.value ?? ''} onChange={e => setCorrection({ ...correction, result: { ...correction.result, value: e.target.value === '' ? null : Number(e.target.value) } })} /></label>{correction.result.movement.unilateral && <label>Άλλη πλευρά<input type="number" min="1" step="1" value={correction.result.otherSide ?? ''} onChange={e => setCorrection({ ...correction, result: { ...correction.result, otherSide: e.target.value === '' ? null : Number(e.target.value) } })} /></label>}</div>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={() => setCorrection(null)}>Ακύρωση</Button><Button type="submit" disabled={saving || (correction.result.status !== 'skipped' && !validResult(correction.result))}><Check size={16} />Αποθήκευση</Button></div></form>}</Modal>
  </>
}
function downloadSession(workout: Workout) {
  const quote = (value: unknown) => { let text = String(value ?? ''); if (/^[=+@\-\t\r]/.test(text)) text = `'${text}`; return `"${text.replaceAll('"', '""')}"` }
  const rows = [['Αθλήτρια', 'Άσκηση', 'Σετ', 'Βάρος kg ανά αλτήρα', 'Επαναλήψεις', 'Δευτερόλεπτα', 'Άλλη πλευρά', 'Κατάσταση'], ...Object.values(workout.results).filter(r => r.status !== 'pending').map(r => [athletes[r.athlete].name, r.movement.name, r.round + 1, r.weight, r.movement.metric === 'reps' ? r.value : '', r.movement.metric === 'seconds' ? r.value : '', r.otherSide, r.status])]
  const url = URL.createObjectURL(new Blob(['\ufeff' + rows.map(row => row.map(quote).join(',')).join('\n')], { type: 'text/csv;charset=utf-8' }))
  const link = document.createElement('a'); link.href = url; link.download = `workout-${workout.startedAt.slice(0, 10)}.csv`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 500)
}
