import { useMemo, useState } from 'react'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Plus, TrendingUp, Target, Scale, Pencil, Check, ArrowDownRight } from 'lucide-react'
import { useWorkspace } from '../context/Workspace'
import { useAuth } from '../context/Auth'
import { athleteIds, athletes, formatDate, today, weightStats, type AthleteId, type WeighIn } from '../lib/model'
import { number, signed } from '../lib/utils'
import { Badge, Button, Card, EmptyState, Modal, ProgressBar, SectionHeading } from '../components/ui'

export function Progress() {
  const { data, edit } = useWorkspace(), { identity } = useAuth()
  const [form, setForm] = useState<{ id?: string; athlete: AthleteId; date: string; weight: string } | null>(null), [goalForm, setGoalForm] = useState<{ athlete: AthleteId; value: string } | null>(null)
  const [range, setRange] = useState('all'), [chartMode, setChartMode] = useState<'kg' | 'percent'>('kg'), [busy, setBusy] = useState(false)
  const stats = { anna: weightStats(data.weighIns, 'anna'), dimitra: weightStats(data.weighIns, 'dimitra') }
  const rows = [...data.weighIns].sort((a, b) => b.date.localeCompare(a.date) || b.createdAt.localeCompare(a.createdAt))
  const chartData = useMemo(() => {
    const byDate = new Map<string, Record<string, string | number>>()
    const cutoff = new Date(); cutoff.setDate(cutoff.getDate() - Number(range))
    for (const entry of [...data.weighIns].sort((a, b) => a.createdAt.localeCompare(b.createdAt))) {
      if (range !== 'all' && new Date(entry.date + 'T12:00:00Z') < cutoff) continue
      const point = byDate.get(entry.date) || { date: entry.date }
      const first = stats[entry.athlete].first
      point[entry.athlete] = chartMode === 'kg' ? entry.weight : first ? Math.round((entry.weight - first.weight) / first.weight * 1000) / 10 : 0
      byDate.set(entry.date, point)
    }
    return [...byDate.values()].sort((a, b) => String(a.date).localeCompare(String(b.date)))
  }, [data.weighIns, range, chartMode])
  const newMeasurement = () => setForm({ athlete: identity?.athleteId || 'anna', date: today(), weight: '' })
  return <><div className="page-heading"><div><span className="eyebrow">ΔΥΟ ΔΙΑΔΡΟΜΕΣ ΠΡΟΟΔΟΥ</span><h1>Κάθε μικρό βήμα<span className="title-dot">.</span></h1><p>Οι πραγματικές μετρήσεις και οι προσωπικοί στόχοι μας.</p></div><Button onClick={newMeasurement}><Plus size={17} />Νέα μέτρηση</Button></div>
    <div className="weight-cards">{athleteIds.map(a => { const s = stats[a], goal = data.goals[a].value, distance = s.latest && goal !== null ? Math.abs(s.latest.weight - goal) : null; const percent = s.first && s.latest && goal !== null ? s.first.weight === goal ? (s.latest.weight === goal ? 100 : 0) : Math.min(100, Math.max(0, (s.first.weight - s.latest.weight) / (s.first.weight - goal) * 100)) : null; return <Card className={`weight-card ${a}`} key={a}><div className="weight-card-heading"><span className={`avatar ${a}`}>{athletes[a].initial}</span><div><h3>{athletes[a].name}</h3><small>{s.latest ? `Τελευταία μέτρηση · ${formatDate(s.latest.date)}` : 'Χωρίς μέτρηση ακόμη'}</small></div><Scale size={21} /></div><div className="current-weight">{s.latest ? number(s.latest.weight) : '—'}<span>kg</span></div><div className="weight-card-details"><div><span>Από την αρχή</span><strong className={s.change !== null && s.change < 0 ? 'positive-change' : ''}>{s.change === null ? '—' : <>{signed(s.change)} <small>kg</small></>}</strong></div><div><span>Προηγούμενη μέτρηση</span><strong>{s.previousChange === null ? '—' : `${signed(s.previousChange)} kg`}</strong></div></div><div className="goal-line"><span><Target size={15} />Στόχος: <strong>{goal === null ? 'Δεν έχει οριστεί' : `${number(goal)} kg`}</strong></span>{identity?.role === 'coach' && <button className="icon-link" aria-label={`Ορισμός στόχου ${athletes[a].name}`} onClick={() => setGoalForm({ athlete: a, value: goal === null ? '' : String(goal) })}><Pencil size={14} /></button>}</div>{percent !== null && <><ProgressBar value={percent} /><span className="goal-caption">{distance === 0 ? 'Ο στόχος επιτεύχθηκε.' : `${number(distance!)} kg από τον στόχο`}</span></>}</Card> })}</div>
    <Card className="chart-card"><SectionHeading title="Η εξέλιξή μας" subtitle="Σύγκριση μετρήσεων, με κοινό άξονα χρόνου." action={<select aria-label="Χρονικό εύρος" value={range} onChange={e => setRange(e.target.value)}><option value="all">Όλες οι μετρήσεις</option><option value="28">4 εβδομάδες</option><option value="84">12 εβδομάδες</option></select>} /><div className="chart-toolbar"><div className="chart-legend">{athleteIds.map(a => <span key={a}><i style={{ background: athletes[a].color }} />{athletes[a].name}</span>)}</div><div className="segmented compact"><button className={chartMode === 'kg' ? 'selected' : ''} onClick={() => setChartMode('kg')}>Βάρος · kg</button><button className={chartMode === 'percent' ? 'selected' : ''} onClick={() => setChartMode('percent')}>Μεταβολή · %</button></div></div>{chartData.length ? <div className="weight-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData} margin={{ top: 15, right: 20, bottom: 10, left: 0 }}><CartesianGrid strokeDasharray="4 4" vertical={false} stroke="var(--border)" /><XAxis dataKey="date" tickFormatter={value => formatDate(value)} tickLine={false} axisLine={false} tick={{ fill: 'var(--muted)', fontSize: 12 }} /><YAxis domain={['auto', 'auto']} tickLine={false} axisLine={false} tick={{ fill: 'var(--muted)', fontSize: 12 }} width={48} unit={chartMode === 'kg' ? '' : '%'} /><Tooltip labelFormatter={label => formatDate(String(label), true)} formatter={(value, name) => [`${number(Number(value))} ${chartMode === 'kg' ? 'kg' : '%'}`, name]} contentStyle={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 12, color: 'var(--text)' }} />{athleteIds.map(a => <Line key={a} type="linear" name={athletes[a].name} dataKey={a} stroke={athletes[a].color} strokeWidth={2.5} dot={{ r: 4, strokeWidth: 2 }} activeDot={{ r: 6 }} connectNulls />)}</LineChart></ResponsiveContainer></div> : <div className="empty-chart"><span className="empty-chart-grid" /><EmptyState icon={<TrendingUp size={31} />} title="Η πρόοδος ξεκινά με την πρώτη μέτρηση." description={data.weighIns.length ? 'Δεν υπάρχουν μετρήσεις σε αυτό το χρονικό εύρος.' : 'Προσθέστε πραγματικές μετρήσεις για να δείτε την εξέλιξή τους εδώ.'} action={<Button variant="secondary" onClick={newMeasurement}><Plus size={16} />Προσθήκη μέτρησης</Button>} /></div>}</Card>
    <Card className="weighin-card"><SectionHeading title="Μετρήσεις βάρους" subtitle="Οι ημερομηνίες και οι τιμές που καταγράψατε." action={<Badge>{rows.length} μετρήσεις</Badge>} />{rows.length ? <div className="table-scroll"><table className="weighin-table"><thead><tr><th>Ημερομηνία</th><th>Αθλήτρια</th><th>Βάρος</th><th /></tr></thead><tbody>{rows.map(entry => <tr key={entry.id}><td>{formatDate(entry.date, true)}</td><td><span className={`athlete-label ${entry.athlete}`}><i />{athletes[entry.athlete].name}</span></td><td><strong>{number(entry.weight)}</strong> kg</td><td>{identity?.role === 'coach' && <button className="icon-link" aria-label={`Διόρθωση μέτρησης ${athletes[entry.athlete].name} ${entry.date}`} onClick={() => setForm({ id: entry.id, athlete: entry.athlete, date: entry.date, weight: String(entry.weight) })}><Pencil size={15} /></button>}</td></tr>)}</tbody></table></div> : <div className="empty-row"><Scale size={20} /><span>Δεν έχουν προστεθεί μετρήσεις ακόμη.</span></div>}</Card>
    <Modal open={Boolean(form)} onOpenChange={open => !open && setForm(null)} title={form?.id ? 'Διόρθωση μέτρησης' : 'Νέα μέτρηση βάρους'} description="Καταγράψτε την πραγματική μέτρηση και την ημερομηνία της.">{form && <form onSubmit={async e => { e.preventDefault(); setBusy(true); try { await edit(w => { const previous = w.weighIns.find(x => x.id === form.id); const entry: WeighIn = { id: previous?.id || crypto.randomUUID(), athlete: identity?.role === 'athlete' ? identity.athleteId! : form.athlete, date: form.date, weight: Number(form.weight), revision: previous?.revision || 0, createdAt: previous?.createdAt || new Date().toISOString() }; if (!(entry.weight > 0 && entry.weight < 1000) || entry.date > today()) throw new Error('Ελέγξτε το βάρος και την ημερομηνία.'); w.weighIns = [...w.weighIns.filter(x => x.id !== entry.id), entry]; return [{ kind: 'weighin', payload: entry }] }); setForm(null) } catch { /* context error */ } finally { setBusy(false) } }}><label>Αθλήτρια<select disabled={identity?.role === 'athlete'} value={form.athlete} onChange={e => setForm({ ...form, athlete: e.target.value as AthleteId })}>{athleteIds.map(a => <option value={a} key={a}>{athletes[a].name}</option>)}</select></label><div className="form-grid"><label>Ημερομηνία<input type="date" required max={today()} value={form.date} onChange={e => setForm({ ...form, date: e.target.value })} /></label><label>Βάρος (kg)<input type="number" inputMode="decimal" min="0.1" max="999.9" step="0.1" required autoFocus value={form.weight} onChange={e => setForm({ ...form, weight: e.target.value })} /></label></div><div className="modal-actions"><Button type="button" variant="secondary" onClick={() => setForm(null)}>Ακύρωση</Button><Button type="submit" disabled={busy || !(Number(form.weight) > 0)}><Check size={16} />Αποθήκευση μέτρησης</Button></div></form>}</Modal>
    <Modal open={Boolean(goalForm)} onOpenChange={open => !open && setGoalForm(null)} title="Προσωπικός στόχος" description={goalForm ? athletes[goalForm.athlete].name : ''}>{goalForm && <form onSubmit={async e => { e.preventDefault(); try { await edit(w => { const goal = { ...w.goals[goalForm.athlete], value: goalForm.value === '' ? null : Number(goalForm.value) }; if (goal.value !== null && !(goal.value > 0 && goal.value < 1000)) throw new Error('Ο στόχος πρέπει να είναι θετικό βάρος.'); w.goals[goalForm.athlete] = goal; return [{ kind: 'goal', payload: goal }] }); setGoalForm(null) } catch { /* context error */ } }}><label>Στόχος βάρους (kg)<input type="number" min="0.1" max="999.9" step="0.1" placeholder="Δεν έχει οριστεί" value={goalForm.value} onChange={e => setGoalForm({ ...goalForm, value: e.target.value })} /></label><p className="muted small">Αφήστε το κενό για να αφαιρέσετε τον στόχο.</p><div className="modal-actions"><Button variant="secondary" type="button" onClick={() => setGoalForm(null)}>Ακύρωση</Button><Button type="submit"><Check size={16} />Αποθήκευση στόχου</Button></div></form>}</Modal>
  </>
}
