import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, ArrowRight, ArrowLeftRight, Check, ChevronLeft, Dumbbell, Flag, LockKeyhole, SkipForward, Timer, Trophy, Undo2, CheckCheck } from 'lucide-react'
import { useWorkspace } from '../context/Workspace'
import { useAuth } from '../context/Auth'
import { useTimer } from '../context/Timer'
import { athleteIds, athletes, advanceWorkout, allExpected, blankResult, finishWorkout, formatTarget, isRecorded, movementsFor, progress, requiredResults, slotFor, validResult, type AthleteId, type Movement, type SetResult, type Workout as WorkoutType } from '../lib/model'
import { number } from '../lib/utils'
import { Button, Card, Badge, EmptyState, Modal, ProgressBar } from '../components/ui'

export function Workout() {
  const { id } = useParams(), { data, edit } = useWorkspace(), { identity } = useAuth(), timer = useTimer(), navigate = useNavigate()
  const workout = data.workouts.find(w => w.id === id), [finishing, setFinishing] = useState(false), [busy, setBusy] = useState(false)
  useEffect(() => {
    let lock: WakeLockSentinel | null = null
    const acquire = async () => { if ('wakeLock' in navigator && document.visibilityState === 'visible') { try { lock = await navigator.wakeLock.request('screen') } catch { /* optional browser capability */ } } }
    void acquire(); document.addEventListener('visibilitychange', acquire)
    return () => { document.removeEventListener('visibilitychange', acquire); void lock?.release() }
  }, [])
  if (!workout || workout.status !== 'active' || identity?.role !== 'coach') return <EmptyState icon={<Dumbbell size={30} />} title="Δεν υπάρχει ενεργή προπόνηση εδώ." description="Επιλέξτε προπόνηση από την επισκόπηση ή δείτε τις προηγούμενες στο ιστορικό." action={<Button onClick={() => navigate('/')}>Στην επισκόπηση<ArrowRight size={17} /></Button>} />
  const station = workout.routine.stations[workout.stationIndex], state = progress(workout)
  const update = async (fn: (w: WorkoutType) => WorkoutType) => {
    try { await edit(workspace => { const index = workspace.workouts.findIndex(w => w.id === id); const value = fn(workspace.workouts[index]); workspace.workouts[index] = value; return [{ kind: 'workout', payload: value }] }) } catch { /* context displays error */ }
  }
  const last = workout.stationIndex === workout.routine.stations.length - 1 && workout.roundIndex === station.rounds - 1 && workout.phase === 1
  const ready = requiredResults(workout, workout.phase === 0).every(isRecorded)
  const next = async () => { if (last) setFinishing(true); else await update(advanceWorkout) }
  const back = () => update(w => w.phase === 1 ? { ...w, phase: 0 } : w.roundIndex > 0 ? { ...w, phase: 1, roundIndex: w.roundIndex - 1 } : w.stationIndex > 0 ? { ...w, stationIndex: w.stationIndex - 1, phase: 1, roundIndex: w.routine.stations[w.stationIndex - 1].rounds - 1 } : w)
  return <><div className="page-heading workout-heading"><div><button className="back-link" onClick={() => navigate('/')}><ArrowLeft size={16} />Επισκόπηση</button><h1>{workout.routine.name}<span className="title-dot">.</span></h1><p>{workout.routine.focus}</p></div><div className="workout-heading-actions"><Badge className="live-badge"><span className="live-dot" />ΣΕ ΕΞΕΛΙΞΗ</Badge><Button variant="secondary" onClick={() => setFinishing(true)}><Flag size={17} />Ολοκλήρωση</Button></div></div>
    <Card className="station-navigation">{workout.routine.stations.map((s, i) => <div className={`station-step ${i === workout.stationIndex ? 'current' : i < workout.stationIndex ? 'past' : ''}`} key={s.id}><span>{i < workout.stationIndex ? <Check size={16} /> : String(i + 1).padStart(2, '0')}</span><div><strong>{s.name}</strong><small>{s.rounds} γύροι · {s.rest === null ? 'χωρίς preset' : `${s.rest}″ rest`}</small></div></div>)}</Card>
    <div className="round-heading"><div><span className="eyebrow">{station.name.toUpperCase()}</span><h2>Γύρος {workout.roundIndex + 1} <span>/ {station.rounds}</span></h2></div><div className="round-phase"><span className={workout.phase === 0 ? 'active' : 'done'}>1 <small>Αρχικό ζεύγος</small></span><ArrowLeftRight size={17} /><span className={workout.phase === 1 ? 'active' : ''}>2 <small>Αλλαγή ασκήσεων</small></span></div></div>
    <div className="athlete-panels">{athleteIds.map(a => <AthletePanel key={a} athlete={a} workout={workout} update={update} present={workout.participants.includes(a)} />)}</div>
    <Card className="workout-control"><div className="rest-reminder"><Timer size={21} /><div><strong>{workout.phase === 0 ? 'Δύο ασκήσεις, χωρίς ενδιάμεσο διάλειμμα.' : station.rest === null ? 'Ελάχιστο διάλειμμα, όταν το επιλέξετε.' : `${station.rest}″ διάλειμμα μετά το ζεύγος.`}</strong><small>Το χρονόμετρο ξεκινά μόνο με το δικό σας πάτημα.</small></div><Button variant="secondary" onClick={timer.open}><Timer size={17} /><span>Χρονόμετρο</span></Button></div><div className="workout-navigation"><Button variant="ghost" disabled={workout.phase === 0 && workout.roundIndex === 0 && workout.stationIndex === 0} onClick={() => void back()}><ChevronLeft size={17} />Πίσω</Button><span>{ready ? 'Το ζεύγος έχει καταγραφεί.' : 'Καταγράψτε ή παραλείψτε τις ασκήσεις για συνέχεια.'}</span><Button disabled={!ready} onClick={() => void next()}>{workout.phase === 0 ? <><ArrowLeftRight size={17} />Αλλαγή ασκήσεων</> : last ? <><CheckCheck size={17} />Ολοκλήρωση</> : <>{workout.roundIndex + 1 === station.rounds ? 'Επόμενος σταθμός' : 'Επόμενος γύρος'}<ArrowRight size={17} /></>}</Button></div></Card>
    <div className="session-progress"><span>Πρόοδος προπόνησης</span><ProgressBar value={state.percent} /><strong>{state.recorded}/{state.total}</strong></div>
    <Modal open={finishing} onOpenChange={setFinishing} title="Ολοκλήρωση προπόνησης" description="Η καταγραφή μένει αποθηκευμένη, ακόμη και χωρίς σύνδεση."><div className="finish-summary"><span className="finish-icon"><Trophy size={30} /></span><h3>{workout.routine.name}</h3><p>{Object.values(workout.results).filter(r => r.status === 'completed').length} από {state.total} αποτελέσματα έχουν ολοκληρωθεί.</p></div>{allExpected(workout).some(r => workout.results[r.key]?.status !== 'completed') && <div className="inline-notice">Οι ασκήσεις που δεν ολοκληρώθηκαν θα σημειωθούν ως παραλειφθείσες. Η προπόνηση θα αποθηκευτεί ως μερική.</div>}<div className="modal-actions"><Button variant="secondary" onClick={() => setFinishing(false)}>Συνέχεια προπόνησης</Button><Button disabled={busy} onClick={async () => { setBusy(true); try { await edit(w => { const index = w.workouts.findIndex(x => x.id === id); const finished = finishWorkout(w.workouts[index]); w.workouts[index] = finished; return [{ kind: 'workout', payload: finished }] }); navigate(`/history?session=${id}`) } catch { setBusy(false) } }}><Check size={17} />Αποθήκευση & τέλος</Button></div></Modal>
  </>
}
function AthletePanel({ athlete, workout, update, present }: { athlete: AthleteId; workout: WorkoutType; update: (fn: (w: WorkoutType) => WorkoutType) => Promise<void>; present: boolean }) {
  const { data, edit } = useWorkspace(), station = workout.routine.stations[workout.stationIndex], slotIndex = slotFor(athlete, workout.phase), slot = station.slots[slotIndex]
  const movements = movementsFor(workout, athlete, station, slotIndex), note = data.notes.find(n => n.workoutId === workout.id && n.athlete === athlete)
  const choiceLocked = Object.values(workout.results).some(r => r.athlete === athlete && r.station === station.id && r.slot === slotIndex && isRecorded(r))
  return <Card className={`athlete-panel ${athlete}`} data-testid={`panel-${athlete}`}><div className="athlete-panel-header"><span className={`avatar ${athlete}`}>{athletes[athlete].initial}</span><div><h3>{athletes[athlete].name}</h3><span>{present ? `Άσκηση ${slotIndex + 1} · Σετ ${workout.roundIndex + 1}` : 'Δεν συμμετέχει σήμερα'}</span></div><span className="athlete-color-dot" /></div>{present ? <>{slot.alternatives && <label className="alternative-select">Επιλογή άσκησης<select value={movements[0].id} disabled={choiceLocked} onChange={e => { const value = e.target.value; void update(w => ({ ...w, selections: { ...w.selections, [`${athlete}:${station.id}`]: value } })) }}>{slot.movements.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select></label>}{movements.map(m => <MovementLogger key={`${workout.stationIndex}:${workout.roundIndex}:${m.id}`} movement={m} athlete={athlete} workout={workout} slotIndex={slotIndex} update={update} />)}<label className="coach-note"><span><LockKeyhole size={13} />Ιδιωτική σημείωση προπονητή</span><textarea rows={2} maxLength={10000} placeholder="Πώς πήγε αυτό το σετ;" value={note?.text || ''} onChange={e => { const text = e.target.value; void edit(w => { let n = w.notes.find(x => x.workoutId === workout.id && x.athlete === athlete); if (!n) { n = { id: crypto.randomUUID(), workoutId: workout.id, athlete, text, revision: 0 }; w.notes.push(n) } else n.text = text; return [{ kind: 'note', payload: n }] }).catch(() => {}) }} /></label></> : <EmptyState icon={<UsersIcon />} title="Απούσα" description="Δεν θα δημιουργηθούν αποτελέσματα για αυτή την αθλήτρια." />}</Card>
}
function UsersIcon() { return <Dumbbell size={24} /> }
function MovementLogger({ movement, athlete, workout, slotIndex, update }: { movement: Movement; athlete: AthleteId; workout: WorkoutType; slotIndex: number; update: (fn: (w: WorkoutType) => WorkoutType) => Promise<void> }) {
  const { data } = useWorkspace(), blank = blankResult(workout, athlete, movement, slotIndex), result = workout.results[blank.key] || blank, recorded = isRecorded(result)
  const previous = [...data.workouts].filter(w => w.id !== workout.id && w.status !== 'active').sort((a, b) => b.startedAt.localeCompare(a.startedAt)).flatMap(w => Object.values(w.results)).find(r => r.athlete === athlete && r.movement.id === movement.id && r.status === 'completed')
  const setResult = (patch: Partial<SetResult>) => update(w => ({ ...w, results: { ...w.results, [blank.key]: { ...(w.results[blank.key] || blank), ...patch } } }))
  return <form className={`movement-logger ${recorded ? 'recorded' : ''}`} onSubmit={e => { e.preventDefault(); if (validResult(result)) void setResult({ status: 'completed' }) }}><div className="movement-title"><div><span className="equipment-label"><Dumbbell size={13} />{movement.equipment}</span><h4>{movement.name}</h4></div>{recorded && <Badge className={result.status === 'completed' ? 'complete-badge' : ''}>{result.status === 'completed' ? <Check size={13} /> : <SkipForward size={13} />}{result.status === 'completed' ? 'Έγινε' : 'Παράλειψη'}</Badge>}</div><div className="prescribed-target"><span>Στόχος</span><strong>{formatTarget(movement)}</strong></div><div className={`result-inputs ${!movement.loaded ? 'single-input' : ''}`}>
    {movement.loaded && <div className="weight-input-group"><label htmlFor={`${athlete}-${movement.id}-weight`}>Βάρος <small>kg / αλτήρα</small><input id={`${athlete}-${movement.id}-weight`} type="number" inputMode="decimal" min="0" max="500" step="any" placeholder="—" disabled={recorded} value={result.weight ?? ''} onChange={e => void setResult({ weight: e.target.value === '' ? null : Number(e.target.value) })} /></label><div className="weight-increments" role="group" aria-label={`Αύξηση βάρους ${athletes[athlete].name} ${movement.name}`}>{[1.25, 2.5].map(step => <Button key={step} type="button" variant="secondary" size="small" disabled={recorded || (result.weight ?? 0) + step > 500} aria-label={`Αύξηση ${step} kg ${athletes[athlete].name} ${movement.name}`} onClick={() => void update(w => { const current = w.results[blank.key] || blank; if (isRecorded(current)) return w; const weight = Math.round(((current.weight ?? 0) + step) * 100) / 100; if (weight < 0 || weight > 500 || !Number.isFinite(weight)) return w; return { ...w, results: { ...w.results, [blank.key]: { ...current, weight } } } })}>+{number(step, 2)} kg</Button>)}</div></div>}
    <label htmlFor={`${athlete}-${movement.id}-value`}>{movement.metric === 'seconds' ? 'Διάρκεια' : 'Επαναλήψεις'}<small>{movement.metric === 'seconds' ? 'δευτερόλεπτα' : movement.unilateral === 'leg' ? 'ανά πόδι' : movement.unilateral === 'arm' ? 'ανά χέρι' : 'πραγματικές'}</small><input id={`${athlete}-${movement.id}-value`} type="number" inputMode="numeric" min="1" max="3600" step="1" placeholder="—" disabled={recorded} value={result.value ?? ''} onChange={e => void setResult({ value: e.target.value === '' ? null : Number(e.target.value) })} /></label>
    {movement.unilateral && <label className="other-side-input">Άλλη πλευρά <small>προαιρετικά, αν διαφέρει</small><input aria-label={`Άλλη πλευρά ${athletes[athlete].name} ${movement.name}`} type="number" inputMode="numeric" min="1" step="1" placeholder="ίδιες επαναλήψεις" disabled={recorded} value={result.otherSide ?? ''} onChange={e => void setResult({ otherSide: e.target.value === '' ? null : Number(e.target.value) })} /></label>}
    </div>{previous && <span className="previous-result">Προηγούμενο: {previous.weight !== null ? `${number(previous.weight, 2)} kg · ` : ''}{previous.value} {movement.metric === 'seconds' ? 'δευτ.' : 'επ.'}</span>}<div className="movement-actions">{recorded ? <Button type="button" variant="secondary" onClick={() => void setResult({ status: 'pending' })}><Undo2 size={16} />Αλλαγή καταγραφής</Button> : <><Button type="button" variant="ghost" size="small" onClick={() => void setResult({ status: 'skipped', weight: null, value: null, otherSide: null })}><SkipForward size={15} />Παράλειψη</Button><Button type="submit" disabled={!validResult(result)}><Check size={16} />Καταγραφή</Button></>}</div></form>
}
