import { useState } from 'react'
import { ArrowRight, LockKeyhole, Users, WifiOff } from 'lucide-react'
import { cloud } from '../lib/cloud'
import { useAuth } from '../context/Auth'
import { Button } from './ui'

export function Logo() { return <div className="brand"><span className="brand-mark"><i /><i /><i /><i /></span><span>workout<span className="brand-light">lab</span><small>TRAIN TOGETHER. GROW INDIVIDUALLY.</small></span></div> }
export function Login() {
  const { enterLocal, error: authError } = useAuth()
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  const recovery = location.hash.includes('type=recovery') || new URLSearchParams(location.search).has('recovery')
  return <div className="login-page"><section className="login-story"><Logo /><div><span className="eyebrow">ΤΟ ΔΙΚΟ ΜΑΣ TRAINING SPACE</span><h1>Μαζί στην προπόνηση.<br /><em>Μπροστά στην πρόοδο.</em></h1><p>Δύο αθλήτριες. Ένα πρόγραμμα.<br />Κάθε σετ και κάθε μικρό βήμα, στο ίδιο μέρος.</p><div className="login-features"><span><Users size={18} />Παράλληλη προπόνηση</span><span><WifiOff size={18} />Καταγραφή και offline</span><span><LockKeyhole size={18} />Προσωπικοί λογαριασμοί</span></div></div><span className="login-footer">WORKOUT LAB · YOUR EVERYDAY PROGRESS</span></section><section className="login-form"><div className="login-form-inner"><span className="eyebrow">ΚΑΛΩΣ ΗΡΘΑΤΕ</span><h2>{cloud ? 'Το επόμενο βήμα ξεκινά εδώ.' : 'Γνωρίστε το Workout Lab.'}</h2><p>{cloud ? 'Συνδεθείτε στον προσωπικό σας λογαριασμό.' : 'Δείτε το πρόγραμμά σας και ξεκινήστε την καταγραφή σε αυτή τη συσκευή.'}</p>{cloud ? <form onSubmit={async e => { e.preventDefault(); setBusy(true); const { error } = recovery ? await cloud!.auth.updateUser({ password }) : await cloud!.auth.signInWithPassword({ email, password }); setMessage(error ? 'Η σύνδεση απέτυχε. Ελέγξτε τα στοιχεία σας και τη σύνδεση στο internet.' : ''); if (recovery && !error) { history.replaceState({}, '', location.pathname + '#/'); location.reload() } setBusy(false) }}>
    {!recovery && <label>Email<input type="email" autoComplete="username" required value={email} onChange={e => setEmail(e.target.value)} /></label>}<label>{recovery ? 'Νέος κωδικός' : 'Κωδικός'}<input type="password" minLength={recovery ? 8 : undefined} autoComplete={recovery ? 'new-password' : 'current-password'} required value={password} onChange={e => setPassword(e.target.value)} /></label><Button disabled={busy}>{busy ? 'Σύνδεση…' : recovery ? 'Αλλαγή κωδικού' : 'Σύνδεση'}<ArrowRight size={18} /></Button>{!recovery && <button type="button" className="forgot" disabled={!email || busy} onClick={async () => { setBusy(true); const { error } = await cloud!.auth.resetPasswordForEmail(email, { redirectTo: `${location.origin}${import.meta.env.BASE_URL}?recovery=1` }); setMessage(error ? 'Δεν ήταν δυνατή η αποστολή. Επικοινωνήστε με τον προπονητή.' : 'Αν υπάρχει λογαριασμός, θα λάβετε email επαναφοράς.'); setBusy(false) }}>Ξέχασα τον κωδικό μου</button>}
    </form> : <><div className="local-notice"><WifiOff size={20} /><div><strong>Μόνο σε αυτή τη συσκευή</strong><p>Οι καταγραφές αποθηκεύονται τοπικά. Οι λογαριασμοί και ο συγχρονισμός θα ενεργοποιηθούν μόλις συνδεθεί το cloud.</p></div></div><Button className="full-width" onClick={enterLocal}>Άνοιγμα εφαρμογής<ArrowRight size={18} /></Button></>}{cloud && import.meta.env.DEV && <Button variant="secondary" className="full-width local-preview" onClick={enterLocal}>Προεπισκόπηση στη συσκευή</Button>}{(message || authError) && <p className="form-message" role="status">{message || authError}</p>}<small>Ένας χώρος για την Άννα, τη Δήμητρα και τον προπονητή τους.</small></div></section></div>
}
